local protobuf = require("net.protobuf.protobuf")
local commonreward_pb = require("net.protobuflua.commonreward_pb")
local activityVideo_pb = {}
_ENV = activityVideo_pb
TACTIVITYVIDEO = protobuf.Descriptor()
local TACTIVITYVIDEO_ID_FIELD = protobuf.FieldDescriptor()
TAVIDEOWATCHARG = protobuf.Descriptor()
local TAVIDEOWATCHARG_ID_FIELD = protobuf.FieldDescriptor()
TAVIDEOWATCHRET = protobuf.Descriptor()
local TAVIDEOWATCHRET_BASEREWARD_FIELD = protobuf.FieldDescriptor()
TACTIVITYVIDEO_ID_FIELD.name = "Id"
TACTIVITYVIDEO_ID_FIELD.full_name = ".pb.TActivityVideo.Id"
TACTIVITYVIDEO_ID_FIELD.number = 1
TACTIVITYVIDEO_ID_FIELD.index = 0
TACTIVITYVIDEO_ID_FIELD.label = 3
TACTIVITYVIDEO_ID_FIELD.has_default_value = false
TACTIVITYVIDEO_ID_FIELD.default_value = {}
TACTIVITYVIDEO_ID_FIELD.type = 5
TACTIVITYVIDEO_ID_FIELD.cpp_type = 1
TACTIVITYVIDEO.file_name = activityVideo_pb
TACTIVITYVIDEO.name = "TActivityVideo"
TACTIVITYVIDEO.full_name = ".pb.TActivityVideo"
TACTIVITYVIDEO.nested_types = {}
TACTIVITYVIDEO.enum_types = {}
TACTIVITYVIDEO.fields = {TACTIVITYVIDEO_ID_FIELD}
TACTIVITYVIDEO.is_extendable = false
TACTIVITYVIDEO.extensions = {}
TAVIDEOWATCHARG_ID_FIELD.name = "Id"
TAVIDEOWATCHARG_ID_FIELD.full_name = ".pb.TAVideoWatchArg.Id"
TAVIDEOWATCHARG_ID_FIELD.number = 1
TAVIDEOWATCHARG_ID_FIELD.index = 0
TAVIDEOWATCHARG_ID_FIELD.label = 1
TAVIDEOWATCHARG_ID_FIELD.has_default_value = false
TAVIDEOWATCHARG_ID_FIELD.default_value = nil
TAVIDEOWATCHARG_ID_FIELD.type = 5
TAVIDEOWATCHARG_ID_FIELD.cpp_type = 1
TAVIDEOWATCHARG.file_name = activityVideo_pb
TAVIDEOWATCHARG.name = "TAVideoWatchArg"
TAVIDEOWATCHARG.full_name = ".pb.TAVideoWatchArg"
TAVIDEOWATCHARG.nested_types = {}
TAVIDEOWATCHARG.enum_types = {}
TAVIDEOWATCHARG.fields = {TAVIDEOWATCHARG_ID_FIELD}
TAVIDEOWATCHARG.is_extendable = false
TAVIDEOWATCHARG.extensions = {}
TAVIDEOWATCHRET_BASEREWARD_FIELD.name = "BaseReward"
TAVIDEOWATCHRET_BASEREWARD_FIELD.full_name = ".pb.TAVideoWatchRet.BaseReward"
TAVIDEOWATCHRET_BASEREWARD_FIELD.number = 1
TAVIDEOWATCHRET_BASEREWARD_FIELD.index = 0
TAVIDEOWATCHRET_BASEREWARD_FIELD.label = 3
TAVIDEOWATCHRET_BASEREWARD_FIELD.has_default_value = false
TAVIDEOWATCHRET_BASEREWARD_FIELD.default_value = {}
TAVIDEOWATCHRET_BASEREWARD_FIELD.message_type = commonreward_pb.TCOMMONREWARD
TAVIDEOWATCHRET_BASEREWARD_FIELD.type = 11
TAVIDEOWATCHRET_BASEREWARD_FIELD.cpp_type = 10
TAVIDEOWATCHRET.file_name = activityVideo_pb
TAVIDEOWATCHRET.name = "TAVideoWatchRet"
TAVIDEOWATCHRET.full_name = ".pb.TAVideoWatchRet"
TAVIDEOWATCHRET.nested_types = {}
TAVIDEOWATCHRET.enum_types = {}
TAVIDEOWATCHRET.fields = {TAVIDEOWATCHRET_BASEREWARD_FIELD}
TAVIDEOWATCHRET.is_extendable = false
TAVIDEOWATCHRET.extensions = {}
TAVideoWatchArg = protobuf.Message(TAVIDEOWATCHARG)
TAVideoWatchRet = protobuf.Message(TAVIDEOWATCHRET)
TActivityVideo = protobuf.Message(TACTIVITYVIDEO)
return _ENV
