local protobuf = require("net.protobuf.protobuf")
local activity_pb = {}
_ENV = activity_pb
TRETACTIVITYINFO = protobuf.Descriptor()
local TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD = protobuf.FieldDescriptor()
local TRETACTIVITYINFO_TIME_FIELD = protobuf.FieldDescriptor()
local TRETACTIVITYINFO_VERSION_FIELD = protobuf.FieldDescriptor()
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.name = "ActivityIdList"
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.full_name = ".pb.TRetActivityInfo.ActivityIdList"
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.number = 1
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.index = 0
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.label = 3
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.has_default_value = false
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.default_value = {}
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.type = 5
TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD.cpp_type = 1
TRETACTIVITYINFO_TIME_FIELD.name = "Time"
TRETACTIVITYINFO_TIME_FIELD.full_name = ".pb.TRetActivityInfo.Time"
TRETACTIVITYINFO_TIME_FIELD.number = 2
TRETACTIVITYINFO_TIME_FIELD.index = 1
TRETACTIVITYINFO_TIME_FIELD.label = 1
TRETACTIVITYINFO_TIME_FIELD.has_default_value = false
TRETACTIVITYINFO_TIME_FIELD.default_value = nil
TRETACTIVITYINFO_TIME_FIELD.type = 5
TRETACTIVITYINFO_TIME_FIELD.cpp_type = 1
TRETACTIVITYINFO_VERSION_FIELD.name = "Version"
TRETACTIVITYINFO_VERSION_FIELD.full_name = ".pb.TRetActivityInfo.Version"
TRETACTIVITYINFO_VERSION_FIELD.number = 3
TRETACTIVITYINFO_VERSION_FIELD.index = 2
TRETACTIVITYINFO_VERSION_FIELD.label = 1
TRETACTIVITYINFO_VERSION_FIELD.has_default_value = false
TRETACTIVITYINFO_VERSION_FIELD.default_value = nil
TRETACTIVITYINFO_VERSION_FIELD.type = 5
TRETACTIVITYINFO_VERSION_FIELD.cpp_type = 1
TRETACTIVITYINFO.file_name = activity_pb
TRETACTIVITYINFO.name = "TRetActivityInfo"
TRETACTIVITYINFO.full_name = ".pb.TRetActivityInfo"
TRETACTIVITYINFO.nested_types = {}
TRETACTIVITYINFO.enum_types = {}
TRETACTIVITYINFO.fields = {
  TRETACTIVITYINFO_ACTIVITYIDLIST_FIELD,
  TRETACTIVITYINFO_TIME_FIELD,
  TRETACTIVITYINFO_VERSION_FIELD
}
TRETACTIVITYINFO.is_extendable = false
TRETACTIVITYINFO.extensions = {}
TRetActivityInfo = protobuf.Message(TRETACTIVITYINFO)
return _ENV
