local protobuf = require("net.protobuf.protobuf")
local battleplayer_pb = require("net.protobuflua.battleplayer_pb")
local battleenemy_pb = {}
_ENV = battleenemy_pb
TBATTLEENEMYFLEET = protobuf.Descriptor()
local TBATTLEENEMYFLEET_FLEETID_FIELD = protobuf.FieldDescriptor()
local TBATTLEENEMYFLEET_STATE_FIELD = protobuf.FieldDescriptor()
local TBATTLEENEMYFLEET_SHIPS_FIELD = protobuf.FieldDescriptor()
TBATTLEENEMYSHIP = protobuf.Descriptor()
local TBATTLEENEMYSHIP_SHIPID_FIELD = protobuf.FieldDescriptor()
local TBATTLEENEMYSHIP_ATTR_FIELD = protobuf.FieldDescriptor()
local TBATTLEENEMYSHIP_PSKILL_FIELD = protobuf.FieldDescriptor()
TBATTLEENEMYFLEET_FLEETID_FIELD.name = "FleetId"
TBATTLEENEMYFLEET_FLEETID_FIELD.full_name = ".pb.TBattleEnemyFleet.FleetId"
TBATTLEENEMYFLEET_FLEETID_FIELD.number = 1
TBATTLEENEMYFLEET_FLEETID_FIELD.index = 0
TBATTLEENEMYFLEET_FLEETID_FIELD.label = 1
TBATTLEENEMYFLEET_FLEETID_FIELD.has_default_value = false
TBATTLEENEMYFLEET_FLEETID_FIELD.default_value = nil
TBATTLEENEMYFLEET_FLEETID_FIELD.type = 5
TBATTLEENEMYFLEET_FLEETID_FIELD.cpp_type = 1
TBATTLEENEMYFLEET_STATE_FIELD.name = "State"
TBATTLEENEMYFLEET_STATE_FIELD.full_name = ".pb.TBattleEnemyFleet.State"
TBATTLEENEMYFLEET_STATE_FIELD.number = 2
TBATTLEENEMYFLEET_STATE_FIELD.index = 1
TBATTLEENEMYFLEET_STATE_FIELD.label = 1
TBATTLEENEMYFLEET_STATE_FIELD.has_default_value = false
TBATTLEENEMYFLEET_STATE_FIELD.default_value = nil
TBATTLEENEMYFLEET_STATE_FIELD.type = 5
TBATTLEENEMYFLEET_STATE_FIELD.cpp_type = 1
TBATTLEENEMYFLEET_SHIPS_FIELD.name = "Ships"
TBATTLEENEMYFLEET_SHIPS_FIELD.full_name = ".pb.TBattleEnemyFleet.Ships"
TBATTLEENEMYFLEET_SHIPS_FIELD.number = 3
TBATTLEENEMYFLEET_SHIPS_FIELD.index = 2
TBATTLEENEMYFLEET_SHIPS_FIELD.label = 3
TBATTLEENEMYFLEET_SHIPS_FIELD.has_default_value = false
TBATTLEENEMYFLEET_SHIPS_FIELD.default_value = {}
TBATTLEENEMYFLEET_SHIPS_FIELD.message_type = TBATTLEENEMYSHIP
TBATTLEENEMYFLEET_SHIPS_FIELD.type = 11
TBATTLEENEMYFLEET_SHIPS_FIELD.cpp_type = 10
TBATTLEENEMYFLEET.file_name = battleenemy_pb
TBATTLEENEMYFLEET.name = "TBattleEnemyFleet"
TBATTLEENEMYFLEET.full_name = ".pb.TBattleEnemyFleet"
TBATTLEENEMYFLEET.nested_types = {}
TBATTLEENEMYFLEET.enum_types = {}
TBATTLEENEMYFLEET.fields = {
  TBATTLEENEMYFLEET_FLEETID_FIELD,
  TBATTLEENEMYFLEET_STATE_FIELD,
  TBATTLEENEMYFLEET_SHIPS_FIELD
}
TBATTLEENEMYFLEET.is_extendable = false
TBATTLEENEMYFLEET.extensions = {}
TBATTLEENEMYSHIP_SHIPID_FIELD.name = "ShipId"
TBATTLEENEMYSHIP_SHIPID_FIELD.full_name = ".pb.TBattleEnemyShip.ShipId"
TBATTLEENEMYSHIP_SHIPID_FIELD.number = 1
TBATTLEENEMYSHIP_SHIPID_FIELD.index = 0
TBATTLEENEMYSHIP_SHIPID_FIELD.label = 1
TBATTLEENEMYSHIP_SHIPID_FIELD.has_default_value = false
TBATTLEENEMYSHIP_SHIPID_FIELD.default_value = nil
TBATTLEENEMYSHIP_SHIPID_FIELD.type = 5
TBATTLEENEMYSHIP_SHIPID_FIELD.cpp_type = 1
TBATTLEENEMYSHIP_ATTR_FIELD.name = "Attr"
TBATTLEENEMYSHIP_ATTR_FIELD.full_name = ".pb.TBattleEnemyShip.Attr"
TBATTLEENEMYSHIP_ATTR_FIELD.number = 2
TBATTLEENEMYSHIP_ATTR_FIELD.index = 1
TBATTLEENEMYSHIP_ATTR_FIELD.label = 3
TBATTLEENEMYSHIP_ATTR_FIELD.has_default_value = false
TBATTLEENEMYSHIP_ATTR_FIELD.default_value = {}
TBATTLEENEMYSHIP_ATTR_FIELD.message_type = battleplayer_pb.THEROATTR
TBATTLEENEMYSHIP_ATTR_FIELD.type = 11
TBATTLEENEMYSHIP_ATTR_FIELD.cpp_type = 10
TBATTLEENEMYSHIP_PSKILL_FIELD.name = "PSkill"
TBATTLEENEMYSHIP_PSKILL_FIELD.full_name = ".pb.TBattleEnemyShip.PSkill"
TBATTLEENEMYSHIP_PSKILL_FIELD.number = 3
TBATTLEENEMYSHIP_PSKILL_FIELD.index = 2
TBATTLEENEMYSHIP_PSKILL_FIELD.label = 3
TBATTLEENEMYSHIP_PSKILL_FIELD.has_default_value = false
TBATTLEENEMYSHIP_PSKILL_FIELD.default_value = {}
TBATTLEENEMYSHIP_PSKILL_FIELD.type = 5
TBATTLEENEMYSHIP_PSKILL_FIELD.cpp_type = 1
TBATTLEENEMYSHIP.file_name = battleenemy_pb
TBATTLEENEMYSHIP.name = "TBattleEnemyShip"
TBATTLEENEMYSHIP.full_name = ".pb.TBattleEnemyShip"
TBATTLEENEMYSHIP.nested_types = {}
TBATTLEENEMYSHIP.enum_types = {}
TBATTLEENEMYSHIP.fields = {
  TBATTLEENEMYSHIP_SHIPID_FIELD,
  TBATTLEENEMYSHIP_ATTR_FIELD,
  TBATTLEENEMYSHIP_PSKILL_FIELD
}
TBATTLEENEMYSHIP.is_extendable = false
TBATTLEENEMYSHIP.extensions = {}
TBattleEnemyFleet = protobuf.Message(TBATTLEENEMYFLEET)
TBattleEnemyShip = protobuf.Message(TBATTLEENEMYSHIP)
return _ENV
