local protobuf = require("net.protobuf.protobuf")
BattleStatistics_pb = {}
local m = BattleStatistics_pb
local g = _G
local rawget = _ENV.rawget
local rawset = _ENV.rawset
_ENV = setmetatable({}, {
  __index = function(t, k)
    return rawget(m, k) or rawget(g, k)
  end,
  __newindex = m
})
STACTORINFO = protobuf.Descriptor()
local STACTORINFO_ACTORID_FIELD = protobuf.FieldDescriptor()
local STACTORINFO_HPNUM_FIELD = protobuf.FieldDescriptor()
local STACTORINFO_HPPERCENT_FIELD = protobuf.FieldDescriptor()
local STACTORINFO_XPNUM_FIELD = protobuf.FieldDescriptor()
local STACTORINFO_DELTAHP_FIELD = protobuf.FieldDescriptor()
STAREAINFO = protobuf.Descriptor()
local STAREAINFO_AREAINDEX_FIELD = protobuf.FieldDescriptor()
local STAREAINFO_DAMAGE_FIELD = protobuf.FieldDescriptor()
local STAREAINFO_HPPERCENT_FIELD = protobuf.FieldDescriptor()
local STAREAINFO_ACTORINFO_FIELD = protobuf.FieldDescriptor()
BATTLESTATISTICS = protobuf.Descriptor()
local BATTLESTATISTICS_WINNER_FIELD = protobuf.FieldDescriptor()
local BATTLESTATISTICS_ROUND_COUNT_FIELD = protobuf.FieldDescriptor()
local BATTLESTATISTICS_AREAINFO_FIELD = protobuf.FieldDescriptor()
STACTORINFO_ACTORID_FIELD.name = "actorId"
STACTORINFO_ACTORID_FIELD.full_name = ".pb.StActorInfo.actorId"
STACTORINFO_ACTORID_FIELD.number = 1
STACTORINFO_ACTORID_FIELD.index = 0
STACTORINFO_ACTORID_FIELD.label = 1
STACTORINFO_ACTORID_FIELD.has_default_value = false
STACTORINFO_ACTORID_FIELD.default_value = nil
STACTORINFO_ACTORID_FIELD.type = 5
STACTORINFO_ACTORID_FIELD.cpp_type = 1
STACTORINFO_HPNUM_FIELD.name = "hpNum"
STACTORINFO_HPNUM_FIELD.full_name = ".pb.StActorInfo.hpNum"
STACTORINFO_HPNUM_FIELD.number = 2
STACTORINFO_HPNUM_FIELD.index = 1
STACTORINFO_HPNUM_FIELD.label = 1
STACTORINFO_HPNUM_FIELD.has_default_value = false
STACTORINFO_HPNUM_FIELD.default_value = nil
STACTORINFO_HPNUM_FIELD.type = 5
STACTORINFO_HPNUM_FIELD.cpp_type = 1
STACTORINFO_HPPERCENT_FIELD.name = "hpPercent"
STACTORINFO_HPPERCENT_FIELD.full_name = ".pb.StActorInfo.hpPercent"
STACTORINFO_HPPERCENT_FIELD.number = 3
STACTORINFO_HPPERCENT_FIELD.index = 2
STACTORINFO_HPPERCENT_FIELD.label = 1
STACTORINFO_HPPERCENT_FIELD.has_default_value = false
STACTORINFO_HPPERCENT_FIELD.default_value = nil
STACTORINFO_HPPERCENT_FIELD.type = 2
STACTORINFO_HPPERCENT_FIELD.cpp_type = 6
STACTORINFO_XPNUM_FIELD.name = "xpNum"
STACTORINFO_XPNUM_FIELD.full_name = ".pb.StActorInfo.xpNum"
STACTORINFO_XPNUM_FIELD.number = 4
STACTORINFO_XPNUM_FIELD.index = 3
STACTORINFO_XPNUM_FIELD.label = 1
STACTORINFO_XPNUM_FIELD.has_default_value = false
STACTORINFO_XPNUM_FIELD.default_value = nil
STACTORINFO_XPNUM_FIELD.type = 5
STACTORINFO_XPNUM_FIELD.cpp_type = 1
STACTORINFO_DELTAHP_FIELD.name = "deltaHp"
STACTORINFO_DELTAHP_FIELD.full_name = ".pb.StActorInfo.deltaHp"
STACTORINFO_DELTAHP_FIELD.number = 5
STACTORINFO_DELTAHP_FIELD.index = 4
STACTORINFO_DELTAHP_FIELD.label = 1
STACTORINFO_DELTAHP_FIELD.has_default_value = false
STACTORINFO_DELTAHP_FIELD.default_value = nil
STACTORINFO_DELTAHP_FIELD.type = 5
STACTORINFO_DELTAHP_FIELD.cpp_type = 1
STACTORINFO.name = "StActorInfo"
STACTORINFO.full_name = ".pb.StActorInfo"
STACTORINFO.nested_types = {}
STACTORINFO.enum_types = {}
STACTORINFO.fields = {
  STACTORINFO_ACTORID_FIELD,
  STACTORINFO_HPNUM_FIELD,
  STACTORINFO_HPPERCENT_FIELD,
  STACTORINFO_XPNUM_FIELD,
  STACTORINFO_DELTAHP_FIELD
}
STACTORINFO.is_extendable = false
STACTORINFO.extensions = {}
STAREAINFO_AREAINDEX_FIELD.name = "areaIndex"
STAREAINFO_AREAINDEX_FIELD.full_name = ".pb.StAreaInfo.areaIndex"
STAREAINFO_AREAINDEX_FIELD.number = 1
STAREAINFO_AREAINDEX_FIELD.index = 0
STAREAINFO_AREAINDEX_FIELD.label = 1
STAREAINFO_AREAINDEX_FIELD.has_default_value = false
STAREAINFO_AREAINDEX_FIELD.default_value = nil
STAREAINFO_AREAINDEX_FIELD.type = 5
STAREAINFO_AREAINDEX_FIELD.cpp_type = 1
STAREAINFO_DAMAGE_FIELD.name = "damage"
STAREAINFO_DAMAGE_FIELD.full_name = ".pb.StAreaInfo.damage"
STAREAINFO_DAMAGE_FIELD.number = 2
STAREAINFO_DAMAGE_FIELD.index = 1
STAREAINFO_DAMAGE_FIELD.label = 1
STAREAINFO_DAMAGE_FIELD.has_default_value = false
STAREAINFO_DAMAGE_FIELD.default_value = nil
STAREAINFO_DAMAGE_FIELD.type = 5
STAREAINFO_DAMAGE_FIELD.cpp_type = 1
STAREAINFO_HPPERCENT_FIELD.name = "hpPercent"
STAREAINFO_HPPERCENT_FIELD.full_name = ".pb.StAreaInfo.hpPercent"
STAREAINFO_HPPERCENT_FIELD.number = 3
STAREAINFO_HPPERCENT_FIELD.index = 2
STAREAINFO_HPPERCENT_FIELD.label = 1
STAREAINFO_HPPERCENT_FIELD.has_default_value = false
STAREAINFO_HPPERCENT_FIELD.default_value = nil
STAREAINFO_HPPERCENT_FIELD.type = 2
STAREAINFO_HPPERCENT_FIELD.cpp_type = 6
STAREAINFO_ACTORINFO_FIELD.name = "actorInfo"
STAREAINFO_ACTORINFO_FIELD.full_name = ".pb.StAreaInfo.actorInfo"
STAREAINFO_ACTORINFO_FIELD.number = 4
STAREAINFO_ACTORINFO_FIELD.index = 3
STAREAINFO_ACTORINFO_FIELD.label = 3
STAREAINFO_ACTORINFO_FIELD.has_default_value = false
STAREAINFO_ACTORINFO_FIELD.default_value = {}
STAREAINFO_ACTORINFO_FIELD.message_type = STACTORINFO
STAREAINFO_ACTORINFO_FIELD.type = 11
STAREAINFO_ACTORINFO_FIELD.cpp_type = 10
STAREAINFO.name = "StAreaInfo"
STAREAINFO.full_name = ".pb.StAreaInfo"
STAREAINFO.nested_types = {}
STAREAINFO.enum_types = {}
STAREAINFO.fields = {
  STAREAINFO_AREAINDEX_FIELD,
  STAREAINFO_DAMAGE_FIELD,
  STAREAINFO_HPPERCENT_FIELD,
  STAREAINFO_ACTORINFO_FIELD
}
STAREAINFO.is_extendable = false
STAREAINFO.extensions = {}
BATTLESTATISTICS_WINNER_FIELD.name = "winner"
BATTLESTATISTICS_WINNER_FIELD.full_name = ".pb.BattleStatistics.winner"
BATTLESTATISTICS_WINNER_FIELD.number = 1
BATTLESTATISTICS_WINNER_FIELD.index = 0
BATTLESTATISTICS_WINNER_FIELD.label = 1
BATTLESTATISTICS_WINNER_FIELD.has_default_value = false
BATTLESTATISTICS_WINNER_FIELD.default_value = nil
BATTLESTATISTICS_WINNER_FIELD.type = 5
BATTLESTATISTICS_WINNER_FIELD.cpp_type = 1
BATTLESTATISTICS_ROUND_COUNT_FIELD.name = "round_count"
BATTLESTATISTICS_ROUND_COUNT_FIELD.full_name = ".pb.BattleStatistics.round_count"
BATTLESTATISTICS_ROUND_COUNT_FIELD.number = 2
BATTLESTATISTICS_ROUND_COUNT_FIELD.index = 1
BATTLESTATISTICS_ROUND_COUNT_FIELD.label = 1
BATTLESTATISTICS_ROUND_COUNT_FIELD.has_default_value = false
BATTLESTATISTICS_ROUND_COUNT_FIELD.default_value = nil
BATTLESTATISTICS_ROUND_COUNT_FIELD.type = 5
BATTLESTATISTICS_ROUND_COUNT_FIELD.cpp_type = 1
BATTLESTATISTICS_AREAINFO_FIELD.name = "areaInfo"
BATTLESTATISTICS_AREAINFO_FIELD.full_name = ".pb.BattleStatistics.areaInfo"
BATTLESTATISTICS_AREAINFO_FIELD.number = 3
BATTLESTATISTICS_AREAINFO_FIELD.index = 2
BATTLESTATISTICS_AREAINFO_FIELD.label = 3
BATTLESTATISTICS_AREAINFO_FIELD.has_default_value = false
BATTLESTATISTICS_AREAINFO_FIELD.default_value = {}
BATTLESTATISTICS_AREAINFO_FIELD.message_type = STAREAINFO
BATTLESTATISTICS_AREAINFO_FIELD.type = 11
BATTLESTATISTICS_AREAINFO_FIELD.cpp_type = 10
BATTLESTATISTICS.name = "BattleStatistics"
BATTLESTATISTICS.full_name = ".pb.BattleStatistics"
BATTLESTATISTICS.nested_types = {}
BATTLESTATISTICS.enum_types = {}
BATTLESTATISTICS.fields = {
  BATTLESTATISTICS_WINNER_FIELD,
  BATTLESTATISTICS_ROUND_COUNT_FIELD,
  BATTLESTATISTICS_AREAINFO_FIELD
}
BATTLESTATISTICS.is_extendable = false
BATTLESTATISTICS.extensions = {}
BattleStatistics = protobuf.Message(BATTLESTATISTICS)
StActorInfo = protobuf.Message(STACTORINFO)
StAreaInfo = protobuf.Message(STAREAINFO)
