local protobuf = require("net.protobuf.protobuf")
book_pb = {}
local m = book_pb
local g = _G
local rawget = _ENV.rawget
local rawset = _ENV.rawset
_ENV = setmetatable({}, {
  __index = function(t, k)
    return rawget(m, k) or rawget(g, k)
  end,
  __newindex = m
})
TBOOKINFO = protobuf.Descriptor()
local TBOOKINFO_BOOKINFO_FIELD = protobuf.FieldDescriptor()
local TBOOKINFO_ACQUIREINFO_FIELD = protobuf.FieldDescriptor()
TUNLOCKARG = protobuf.Descriptor()
local TUNLOCKARG_COMPOSEID_FIELD = protobuf.FieldDescriptor()
TBOOKINFO_BOOKINFO_FIELD.name = "BookInfo"
TBOOKINFO_BOOKINFO_FIELD.full_name = ".pb.TBookInfo.BookInfo"
TBOOKINFO_BOOKINFO_FIELD.number = 1
TBOOKINFO_BOOKINFO_FIELD.index = 0
TBOOKINFO_BOOKINFO_FIELD.label = 3
TBOOKINFO_BOOKINFO_FIELD.has_default_value = false
TBOOKINFO_BOOKINFO_FIELD.default_value = {}
TBOOKINFO_BOOKINFO_FIELD.type = 5
TBOOKINFO_BOOKINFO_FIELD.cpp_type = 1
TBOOKINFO_ACQUIREINFO_FIELD.name = "AcquireInfo"
TBOOKINFO_ACQUIREINFO_FIELD.full_name = ".pb.TBookInfo.AcquireInfo"
TBOOKINFO_ACQUIREINFO_FIELD.number = 2
TBOOKINFO_ACQUIREINFO_FIELD.index = 1
TBOOKINFO_ACQUIREINFO_FIELD.label = 3
TBOOKINFO_ACQUIREINFO_FIELD.has_default_value = false
TBOOKINFO_ACQUIREINFO_FIELD.default_value = {}
TBOOKINFO_ACQUIREINFO_FIELD.type = 5
TBOOKINFO_ACQUIREINFO_FIELD.cpp_type = 1
TBOOKINFO.name = "TBookInfo"
TBOOKINFO.full_name = ".pb.TBookInfo"
TBOOKINFO.nested_types = {}
TBOOKINFO.enum_types = {}
TBOOKINFO.fields = {TBOOKINFO_BOOKINFO_FIELD, TBOOKINFO_ACQUIREINFO_FIELD}
TBOOKINFO.is_extendable = false
TBOOKINFO.extensions = {}
TUNLOCKARG_COMPOSEID_FIELD.name = "ComposeId"
TUNLOCKARG_COMPOSEID_FIELD.full_name = ".pb.TUnlockArg.ComposeId"
TUNLOCKARG_COMPOSEID_FIELD.number = 1
TUNLOCKARG_COMPOSEID_FIELD.index = 0
TUNLOCKARG_COMPOSEID_FIELD.label = 1
TUNLOCKARG_COMPOSEID_FIELD.has_default_value = false
TUNLOCKARG_COMPOSEID_FIELD.default_value = nil
TUNLOCKARG_COMPOSEID_FIELD.type = 5
TUNLOCKARG_COMPOSEID_FIELD.cpp_type = 1
TUNLOCKARG.name = "TUnlockArg"
TUNLOCKARG.full_name = ".pb.TUnlockArg"
TUNLOCKARG.nested_types = {}
TUNLOCKARG.enum_types = {}
TUNLOCKARG.fields = {TUNLOCKARG_COMPOSEID_FIELD}
TUNLOCKARG.is_extendable = false
TUNLOCKARG.extensions = {}
TBookInfo = protobuf.Message(TBOOKINFO)
TUnlockArg = protobuf.Message(TUNLOCKARG)
