local protobuf = require("net.protobuf.protobuf")
local cachedata_pb = {}
_ENV = cachedata_pb
TCACHEDATAARG = protobuf.Descriptor()
local TCACHEDATAARG_KEY_FIELD = protobuf.FieldDescriptor()
TCACHEDATARET = protobuf.Descriptor()
local TCACHEDATARET_RET_FIELD = protobuf.FieldDescriptor()
TCACHEDATAARG_KEY_FIELD.name = "Key"
TCACHEDATAARG_KEY_FIELD.full_name = ".pb.TCacheDataArg.Key"
TCACHEDATAARG_KEY_FIELD.number = 1
TCACHEDATAARG_KEY_FIELD.index = 0
TCACHEDATAARG_KEY_FIELD.label = 1
TCACHEDATAARG_KEY_FIELD.has_default_value = false
TCACHEDATAARG_KEY_FIELD.default_value = nil
TCACHEDATAARG_KEY_FIELD.type = 9
TCACHEDATAARG_KEY_FIELD.cpp_type = 9
TCACHEDATAARG.file_name = cachedata_pb
TCACHEDATAARG.name = "TCacheDataArg"
TCACHEDATAARG.full_name = ".pb.TCacheDataArg"
TCACHEDATAARG.nested_types = {}
TCACHEDATAARG.enum_types = {}
TCACHEDATAARG.fields = {TCACHEDATAARG_KEY_FIELD}
TCACHEDATAARG.is_extendable = false
TCACHEDATAARG.extensions = {}
TCACHEDATARET_RET_FIELD.name = "Ret"
TCACHEDATARET_RET_FIELD.full_name = ".pb.TCacheDataRet.Ret"
TCACHEDATARET_RET_FIELD.number = 1
TCACHEDATARET_RET_FIELD.index = 0
TCACHEDATARET_RET_FIELD.label = 1
TCACHEDATARET_RET_FIELD.has_default_value = false
TCACHEDATARET_RET_FIELD.default_value = nil
TCACHEDATARET_RET_FIELD.type = 9
TCACHEDATARET_RET_FIELD.cpp_type = 9
TCACHEDATARET.file_name = cachedata_pb
TCACHEDATARET.name = "TCacheDataRet"
TCACHEDATARET.full_name = ".pb.TCacheDataRet"
TCACHEDATARET.nested_types = {}
TCACHEDATARET.enum_types = {}
TCACHEDATARET.fields = {TCACHEDATARET_RET_FIELD}
TCACHEDATARET.is_extendable = false
TCACHEDATARET.extensions = {}
TCacheDataArg = protobuf.Message(TCACHEDATAARG)
TCacheDataRet = protobuf.Message(TCACHEDATARET)
return _ENV
