local protobuf = require("net.protobuf.protobuf")
local cmd_pb = {}
_ENV = cmd_pb
TGMARGS = protobuf.Descriptor()
local TGMARGS_CMDMSG_FIELD = protobuf.FieldDescriptor()
TGMRET = protobuf.Descriptor()
local TGMRET_CMDRET_FIELD = protobuf.FieldDescriptor()
TGMARGS_CMDMSG_FIELD.name = "cmdMsg"
TGMARGS_CMDMSG_FIELD.full_name = ".pb.TGMArgs.cmdMsg"
TGMARGS_CMDMSG_FIELD.number = 1
TGMARGS_CMDMSG_FIELD.index = 0
TGMARGS_CMDMSG_FIELD.label = 1
TGMARGS_CMDMSG_FIELD.has_default_value = false
TGMARGS_CMDMSG_FIELD.default_value = nil
TGMARGS_CMDMSG_FIELD.type = 9
TGMARGS_CMDMSG_FIELD.cpp_type = 9
TGMARGS.file_name = cmd_pb
TGMARGS.name = "TGMArgs"
TGMARGS.full_name = ".pb.TGMArgs"
TGMARGS.nested_types = {}
TGMARGS.enum_types = {}
TGMARGS.fields = {TGMARGS_CMDMSG_FIELD}
TGMARGS.is_extendable = false
TGMARGS.extensions = {}
TGMRET_CMDRET_FIELD.name = "cmdRet"
TGMRET_CMDRET_FIELD.full_name = ".pb.TGMRet.cmdRet"
TGMRET_CMDRET_FIELD.number = 1
TGMRET_CMDRET_FIELD.index = 0
TGMRET_CMDRET_FIELD.label = 1
TGMRET_CMDRET_FIELD.has_default_value = false
TGMRET_CMDRET_FIELD.default_value = nil
TGMRET_CMDRET_FIELD.type = 9
TGMRET_CMDRET_FIELD.cpp_type = 9
TGMRET.file_name = cmd_pb
TGMRET.name = "TGMRet"
TGMRET.full_name = ".pb.TGMRet"
TGMRET.nested_types = {}
TGMRET.enum_types = {}
TGMRET.fields = {TGMRET_CMDRET_FIELD}
TGMRET.is_extendable = false
TGMRET.extensions = {}
TGMArgs = protobuf.Message(TGMARGS)
TGMRet = protobuf.Message(TGMRET)
return _ENV
