local protobuf = require("net.protobuf.protobuf")
local count_pb = {}
_ENV = count_pb
TCOUNTDATA = protobuf.Descriptor()
local TCOUNTDATA_COUNT_FIELD = protobuf.FieldDescriptor()
TCOUNT = protobuf.Descriptor()
local TCOUNT_ID_FIELD = protobuf.FieldDescriptor()
local TCOUNT_NUM_FIELD = protobuf.FieldDescriptor()
TCOUNTDATA_COUNT_FIELD.name = "Count"
TCOUNTDATA_COUNT_FIELD.full_name = ".pb.TCountData.Count"
TCOUNTDATA_COUNT_FIELD.number = 1
TCOUNTDATA_COUNT_FIELD.index = 0
TCOUNTDATA_COUNT_FIELD.label = 3
TCOUNTDATA_COUNT_FIELD.has_default_value = false
TCOUNTDATA_COUNT_FIELD.default_value = {}
TCOUNTDATA_COUNT_FIELD.message_type = TCOUNT
TCOUNTDATA_COUNT_FIELD.type = 11
TCOUNTDATA_COUNT_FIELD.cpp_type = 10
TCOUNTDATA.file_name = count_pb
TCOUNTDATA.name = "TCountData"
TCOUNTDATA.full_name = ".pb.TCountData"
TCOUNTDATA.nested_types = {}
TCOUNTDATA.enum_types = {}
TCOUNTDATA.fields = {TCOUNTDATA_COUNT_FIELD}
TCOUNTDATA.is_extendable = false
TCOUNTDATA.extensions = {}
TCOUNT_ID_FIELD.name = "Id"
TCOUNT_ID_FIELD.full_name = ".pb.TCount.Id"
TCOUNT_ID_FIELD.number = 1
TCOUNT_ID_FIELD.index = 0
TCOUNT_ID_FIELD.label = 1
TCOUNT_ID_FIELD.has_default_value = false
TCOUNT_ID_FIELD.default_value = nil
TCOUNT_ID_FIELD.type = 5
TCOUNT_ID_FIELD.cpp_type = 1
TCOUNT_NUM_FIELD.name = "Num"
TCOUNT_NUM_FIELD.full_name = ".pb.TCount.Num"
TCOUNT_NUM_FIELD.number = 2
TCOUNT_NUM_FIELD.index = 1
TCOUNT_NUM_FIELD.label = 1
TCOUNT_NUM_FIELD.has_default_value = false
TCOUNT_NUM_FIELD.default_value = nil
TCOUNT_NUM_FIELD.type = 5
TCOUNT_NUM_FIELD.cpp_type = 1
TCOUNT.file_name = count_pb
TCOUNT.name = "TCount"
TCOUNT.full_name = ".pb.TCount"
TCOUNT.nested_types = {}
TCOUNT.enum_types = {}
TCOUNT.fields = {TCOUNT_ID_FIELD, TCOUNT_NUM_FIELD}
TCOUNT.is_extendable = false
TCOUNT.extensions = {}
TCount = protobuf.Message(TCOUNT)
TCountData = protobuf.Message(TCOUNTDATA)
return _ENV
