local protobuf = require("net.protobuf.protobuf")
draw_pb = {}
local m = draw_pb
local g = _G
local rawget = _ENV.rawget
local rawset = _ENV.rawset
_ENV = setmetatable({}, {
  __index = function(t, k)
    return rawget(m, k) or rawget(g, k)
  end,
  __newindex = m
})
TDRAWARG = protobuf.Descriptor()
local TDRAWARG_EDRAWTYPE = protobuf.EnumDescriptor()
local TDRAWARG_EDRAWTYPE_ONEDRAW_ENUM = protobuf.EnumValueDescriptor()
local TDRAWARG_EDRAWTYPE_TENDRAW_ENUM = protobuf.EnumValueDescriptor()
local TDRAWARG_ECONSUMETYPE = protobuf.EnumDescriptor()
local TDRAWARG_ECONSUMETYPE_FREETIME_ENUM = protobuf.EnumValueDescriptor()
local TDRAWARG_ECONSUMETYPE_ONEITEM_ENUM = protobuf.EnumValueDescriptor()
local TDRAWARG_ECONSUMETYPE_TENITEM_ENUM = protobuf.EnumValueDescriptor()
local TDRAWARG_ECONSUMETYPE_CURRENCY_ENUM = protobuf.EnumValueDescriptor()
local TDRAWARG_DRAWID_FIELD = protobuf.FieldDescriptor()
local TDRAWARG_DRAWTYPE_FIELD = protobuf.FieldDescriptor()
local TDRAWARG_CONSUMETYPE_FIELD = protobuf.FieldDescriptor()
TDRAWRESULT = protobuf.Descriptor()
local TDRAWRESULT_TYPEID_FIELD = protobuf.FieldDescriptor()
local TDRAWRESULT_OBJID_FIELD = protobuf.FieldDescriptor()
local TDRAWRESULT_NUM_FIELD = protobuf.FieldDescriptor()
TDRAWRET = protobuf.Descriptor()
local TDRAWRET_DRAWRESULT_FIELD = protobuf.FieldDescriptor()
TDRAWARG_EDRAWTYPE_ONEDRAW_ENUM.name = "OneDraw"
TDRAWARG_EDRAWTYPE_ONEDRAW_ENUM.index = 0
TDRAWARG_EDRAWTYPE_ONEDRAW_ENUM.number = 1
TDRAWARG_EDRAWTYPE_TENDRAW_ENUM.name = "TenDraw"
TDRAWARG_EDRAWTYPE_TENDRAW_ENUM.index = 1
TDRAWARG_EDRAWTYPE_TENDRAW_ENUM.number = 2
TDRAWARG_EDRAWTYPE.name = "EDrawType"
TDRAWARG_EDRAWTYPE.full_name = ".pb.TDrawArg.EDrawType"
TDRAWARG_EDRAWTYPE.values = {TDRAWARG_EDRAWTYPE_ONEDRAW_ENUM, TDRAWARG_EDRAWTYPE_TENDRAW_ENUM}
TDRAWARG_ECONSUMETYPE_FREETIME_ENUM.name = "FreeTime"
TDRAWARG_ECONSUMETYPE_FREETIME_ENUM.index = 0
TDRAWARG_ECONSUMETYPE_FREETIME_ENUM.number = 1
TDRAWARG_ECONSUMETYPE_ONEITEM_ENUM.name = "OneItem"
TDRAWARG_ECONSUMETYPE_ONEITEM_ENUM.index = 1
TDRAWARG_ECONSUMETYPE_ONEITEM_ENUM.number = 2
TDRAWARG_ECONSUMETYPE_TENITEM_ENUM.name = "TenItem"
TDRAWARG_ECONSUMETYPE_TENITEM_ENUM.index = 2
TDRAWARG_ECONSUMETYPE_TENITEM_ENUM.number = 3
TDRAWARG_ECONSUMETYPE_CURRENCY_ENUM.name = "Currency"
TDRAWARG_ECONSUMETYPE_CURRENCY_ENUM.index = 3
TDRAWARG_ECONSUMETYPE_CURRENCY_ENUM.number = 4
TDRAWARG_ECONSUMETYPE.name = "EConsumeType"
TDRAWARG_ECONSUMETYPE.full_name = ".pb.TDrawArg.EConsumeType"
TDRAWARG_ECONSUMETYPE.values = {
  TDRAWARG_ECONSUMETYPE_FREETIME_ENUM,
  TDRAWARG_ECONSUMETYPE_ONEITEM_ENUM,
  TDRAWARG_ECONSUMETYPE_TENITEM_ENUM,
  TDRAWARG_ECONSUMETYPE_CURRENCY_ENUM
}
TDRAWARG_DRAWID_FIELD.name = "DrawId"
TDRAWARG_DRAWID_FIELD.full_name = ".pb.TDrawArg.DrawId"
TDRAWARG_DRAWID_FIELD.number = 1
TDRAWARG_DRAWID_FIELD.index = 0
TDRAWARG_DRAWID_FIELD.label = 1
TDRAWARG_DRAWID_FIELD.has_default_value = false
TDRAWARG_DRAWID_FIELD.default_value = nil
TDRAWARG_DRAWID_FIELD.type = 5
TDRAWARG_DRAWID_FIELD.cpp_type = 1
TDRAWARG_DRAWTYPE_FIELD.name = "DrawType"
TDRAWARG_DRAWTYPE_FIELD.full_name = ".pb.TDrawArg.DrawType"
TDRAWARG_DRAWTYPE_FIELD.number = 2
TDRAWARG_DRAWTYPE_FIELD.index = 1
TDRAWARG_DRAWTYPE_FIELD.label = 1
TDRAWARG_DRAWTYPE_FIELD.has_default_value = false
TDRAWARG_DRAWTYPE_FIELD.default_value = nil
TDRAWARG_DRAWTYPE_FIELD.enum_type = TDRAWARG_EDRAWTYPE
TDRAWARG_DRAWTYPE_FIELD.type = 14
TDRAWARG_DRAWTYPE_FIELD.cpp_type = 8
TDRAWARG_CONSUMETYPE_FIELD.name = "ConsumeType"
TDRAWARG_CONSUMETYPE_FIELD.full_name = ".pb.TDrawArg.ConsumeType"
TDRAWARG_CONSUMETYPE_FIELD.number = 3
TDRAWARG_CONSUMETYPE_FIELD.index = 2
TDRAWARG_CONSUMETYPE_FIELD.label = 1
TDRAWARG_CONSUMETYPE_FIELD.has_default_value = false
TDRAWARG_CONSUMETYPE_FIELD.default_value = nil
TDRAWARG_CONSUMETYPE_FIELD.enum_type = TDRAWARG_ECONSUMETYPE
TDRAWARG_CONSUMETYPE_FIELD.type = 14
TDRAWARG_CONSUMETYPE_FIELD.cpp_type = 8
TDRAWARG.name = "TDrawArg"
TDRAWARG.full_name = ".pb.TDrawArg"
TDRAWARG.nested_types = {}
TDRAWARG.enum_types = {TDRAWARG_EDRAWTYPE, TDRAWARG_ECONSUMETYPE}
TDRAWARG.fields = {
  TDRAWARG_DRAWID_FIELD,
  TDRAWARG_DRAWTYPE_FIELD,
  TDRAWARG_CONSUMETYPE_FIELD
}
TDRAWARG.is_extendable = false
TDRAWARG.extensions = {}
TDRAWRESULT_TYPEID_FIELD.name = "TypeId"
TDRAWRESULT_TYPEID_FIELD.full_name = ".pb.TDrawResult.TypeId"
TDRAWRESULT_TYPEID_FIELD.number = 1
TDRAWRESULT_TYPEID_FIELD.index = 0
TDRAWRESULT_TYPEID_FIELD.label = 1
TDRAWRESULT_TYPEID_FIELD.has_default_value = false
TDRAWRESULT_TYPEID_FIELD.default_value = nil
TDRAWRESULT_TYPEID_FIELD.type = 5
TDRAWRESULT_TYPEID_FIELD.cpp_type = 1
TDRAWRESULT_OBJID_FIELD.name = "ObjId"
TDRAWRESULT_OBJID_FIELD.full_name = ".pb.TDrawResult.ObjId"
TDRAWRESULT_OBJID_FIELD.number = 2
TDRAWRESULT_OBJID_FIELD.index = 1
TDRAWRESULT_OBJID_FIELD.label = 1
TDRAWRESULT_OBJID_FIELD.has_default_value = false
TDRAWRESULT_OBJID_FIELD.default_value = nil
TDRAWRESULT_OBJID_FIELD.type = 5
TDRAWRESULT_OBJID_FIELD.cpp_type = 1
TDRAWRESULT_NUM_FIELD.name = "Num"
TDRAWRESULT_NUM_FIELD.full_name = ".pb.TDrawResult.Num"
TDRAWRESULT_NUM_FIELD.number = 3
TDRAWRESULT_NUM_FIELD.index = 2
TDRAWRESULT_NUM_FIELD.label = 1
TDRAWRESULT_NUM_FIELD.has_default_value = false
TDRAWRESULT_NUM_FIELD.default_value = nil
TDRAWRESULT_NUM_FIELD.type = 5
TDRAWRESULT_NUM_FIELD.cpp_type = 1
TDRAWRESULT.name = "TDrawResult"
TDRAWRESULT.full_name = ".pb.TDrawResult"
TDRAWRESULT.nested_types = {}
TDRAWRESULT.enum_types = {}
TDRAWRESULT.fields = {
  TDRAWRESULT_TYPEID_FIELD,
  TDRAWRESULT_OBJID_FIELD,
  TDRAWRESULT_NUM_FIELD
}
TDRAWRESULT.is_extendable = false
TDRAWRESULT.extensions = {}
TDRAWRET_DRAWRESULT_FIELD.name = "DrawResult"
TDRAWRET_DRAWRESULT_FIELD.full_name = ".pb.TDrawRet.DrawResult"
TDRAWRET_DRAWRESULT_FIELD.number = 1
TDRAWRET_DRAWRESULT_FIELD.index = 0
TDRAWRET_DRAWRESULT_FIELD.label = 3
TDRAWRET_DRAWRESULT_FIELD.has_default_value = false
TDRAWRET_DRAWRESULT_FIELD.default_value = {}
TDRAWRET_DRAWRESULT_FIELD.message_type = TDRAWRESULT
TDRAWRET_DRAWRESULT_FIELD.type = 11
TDRAWRET_DRAWRESULT_FIELD.cpp_type = 10
TDRAWRET.name = "TDrawRet"
TDRAWRET.full_name = ".pb.TDrawRet"
TDRAWRET.nested_types = {}
TDRAWRET.enum_types = {}
TDRAWRET.fields = {TDRAWRET_DRAWRESULT_FIELD}
TDRAWRET.is_extendable = false
TDRAWRET.extensions = {}
TDrawArg = protobuf.Message(TDRAWARG)
TDrawResult = protobuf.Message(TDRAWRESULT)
TDrawRet = protobuf.Message(TDRAWRET)
