local protobuf = require("net.protobuf.protobuf")
local item_pb = require("net.protobuflua.item_pb")
local exchange_pb = {}
_ENV = exchange_pb
TEXCHANGE = protobuf.Descriptor()
local TEXCHANGE_EXCHANGEINFO_FIELD = protobuf.FieldDescriptor()
TEXCHANGEINFO = protobuf.Descriptor()
local TEXCHANGEINFO_ID_FIELD = protobuf.FieldDescriptor()
local TEXCHANGEINFO_TIMES_FIELD = protobuf.FieldDescriptor()
TEXCHANGEARG = protobuf.Descriptor()
local TEXCHANGEARG_ID_FIELD = protobuf.FieldDescriptor()
local TEXCHANGEARG_CONSUME_FIELD = protobuf.FieldDescriptor()
local TEXCHANGEARG_REWARD_FIELD = protobuf.FieldDescriptor()
local TEXCHANGEARG_TIME_FIELD = protobuf.FieldDescriptor()
TEXCHANGE_EXCHANGEINFO_FIELD.name = "ExchangeInfo"
TEXCHANGE_EXCHANGEINFO_FIELD.full_name = ".pb.TExchange.ExchangeInfo"
TEXCHANGE_EXCHANGEINFO_FIELD.number = 1
TEXCHANGE_EXCHANGEINFO_FIELD.index = 0
TEXCHANGE_EXCHANGEINFO_FIELD.label = 3
TEXCHANGE_EXCHANGEINFO_FIELD.has_default_value = false
TEXCHANGE_EXCHANGEINFO_FIELD.default_value = {}
TEXCHANGE_EXCHANGEINFO_FIELD.message_type = TEXCHANGEINFO
TEXCHANGE_EXCHANGEINFO_FIELD.type = 11
TEXCHANGE_EXCHANGEINFO_FIELD.cpp_type = 10
TEXCHANGE.file_name = exchange_pb
TEXCHANGE.name = "TExchange"
TEXCHANGE.full_name = ".pb.TExchange"
TEXCHANGE.nested_types = {}
TEXCHANGE.enum_types = {}
TEXCHANGE.fields = {TEXCHANGE_EXCHANGEINFO_FIELD}
TEXCHANGE.is_extendable = false
TEXCHANGE.extensions = {}
TEXCHANGEINFO_ID_FIELD.name = "Id"
TEXCHANGEINFO_ID_FIELD.full_name = ".pb.TExchangeInfo.Id"
TEXCHANGEINFO_ID_FIELD.number = 1
TEXCHANGEINFO_ID_FIELD.index = 0
TEXCHANGEINFO_ID_FIELD.label = 1
TEXCHANGEINFO_ID_FIELD.has_default_value = false
TEXCHANGEINFO_ID_FIELD.default_value = nil
TEXCHANGEINFO_ID_FIELD.type = 5
TEXCHANGEINFO_ID_FIELD.cpp_type = 1
TEXCHANGEINFO_TIMES_FIELD.name = "Times"
TEXCHANGEINFO_TIMES_FIELD.full_name = ".pb.TExchangeInfo.Times"
TEXCHANGEINFO_TIMES_FIELD.number = 2
TEXCHANGEINFO_TIMES_FIELD.index = 1
TEXCHANGEINFO_TIMES_FIELD.label = 1
TEXCHANGEINFO_TIMES_FIELD.has_default_value = false
TEXCHANGEINFO_TIMES_FIELD.default_value = nil
TEXCHANGEINFO_TIMES_FIELD.type = 5
TEXCHANGEINFO_TIMES_FIELD.cpp_type = 1
TEXCHANGEINFO.file_name = exchange_pb
TEXCHANGEINFO.name = "TExchangeInfo"
TEXCHANGEINFO.full_name = ".pb.TExchangeInfo"
TEXCHANGEINFO.nested_types = {}
TEXCHANGEINFO.enum_types = {}
TEXCHANGEINFO.fields = {TEXCHANGEINFO_ID_FIELD, TEXCHANGEINFO_TIMES_FIELD}
TEXCHANGEINFO.is_extendable = false
TEXCHANGEINFO.extensions = {}
TEXCHANGEARG_ID_FIELD.name = "Id"
TEXCHANGEARG_ID_FIELD.full_name = ".pb.TExchangeArg.Id"
TEXCHANGEARG_ID_FIELD.number = 1
TEXCHANGEARG_ID_FIELD.index = 0
TEXCHANGEARG_ID_FIELD.label = 1
TEXCHANGEARG_ID_FIELD.has_default_value = false
TEXCHANGEARG_ID_FIELD.default_value = nil
TEXCHANGEARG_ID_FIELD.type = 5
TEXCHANGEARG_ID_FIELD.cpp_type = 1
TEXCHANGEARG_CONSUME_FIELD.name = "Consume"
TEXCHANGEARG_CONSUME_FIELD.full_name = ".pb.TExchangeArg.Consume"
TEXCHANGEARG_CONSUME_FIELD.number = 2
TEXCHANGEARG_CONSUME_FIELD.index = 1
TEXCHANGEARG_CONSUME_FIELD.label = 3
TEXCHANGEARG_CONSUME_FIELD.has_default_value = false
TEXCHANGEARG_CONSUME_FIELD.default_value = {}
TEXCHANGEARG_CONSUME_FIELD.message_type = item_pb.TITEM
TEXCHANGEARG_CONSUME_FIELD.type = 11
TEXCHANGEARG_CONSUME_FIELD.cpp_type = 10
TEXCHANGEARG_REWARD_FIELD.name = "Reward"
TEXCHANGEARG_REWARD_FIELD.full_name = ".pb.TExchangeArg.Reward"
TEXCHANGEARG_REWARD_FIELD.number = 3
TEXCHANGEARG_REWARD_FIELD.index = 2
TEXCHANGEARG_REWARD_FIELD.label = 3
TEXCHANGEARG_REWARD_FIELD.has_default_value = false
TEXCHANGEARG_REWARD_FIELD.default_value = {}
TEXCHANGEARG_REWARD_FIELD.message_type = item_pb.TITEM
TEXCHANGEARG_REWARD_FIELD.type = 11
TEXCHANGEARG_REWARD_FIELD.cpp_type = 10
TEXCHANGEARG_TIME_FIELD.name = "Time"
TEXCHANGEARG_TIME_FIELD.full_name = ".pb.TExchangeArg.Time"
TEXCHANGEARG_TIME_FIELD.number = 4
TEXCHANGEARG_TIME_FIELD.index = 3
TEXCHANGEARG_TIME_FIELD.label = 1
TEXCHANGEARG_TIME_FIELD.has_default_value = false
TEXCHANGEARG_TIME_FIELD.default_value = nil
TEXCHANGEARG_TIME_FIELD.type = 5
TEXCHANGEARG_TIME_FIELD.cpp_type = 1
TEXCHANGEARG.file_name = exchange_pb
TEXCHANGEARG.name = "TExchangeArg"
TEXCHANGEARG.full_name = ".pb.TExchangeArg"
TEXCHANGEARG.nested_types = {}
TEXCHANGEARG.enum_types = {}
TEXCHANGEARG.fields = {
  TEXCHANGEARG_ID_FIELD,
  TEXCHANGEARG_CONSUME_FIELD,
  TEXCHANGEARG_REWARD_FIELD,
  TEXCHANGEARG_TIME_FIELD
}
TEXCHANGEARG.is_extendable = false
TEXCHANGEARG.extensions = {}
TExchange = protobuf.Message(TEXCHANGE)
TExchangeArg = protobuf.Message(TEXCHANGEARG)
TExchangeInfo = protobuf.Message(TEXCHANGEINFO)
return _ENV
