local protobuf = require("net.protobuf.protobuf")
local jopen_pb = {}
_ENV = jopen_pb
TJOPEN = protobuf.Descriptor()
local TJOPEN_FETCHHEROTIME_FIELD = protobuf.FieldDescriptor()
local TJOPEN_FETCHEQUIPTIME_FIELD = protobuf.FieldDescriptor()
TJOPEN_FETCHHEROTIME_FIELD.name = "FetchHeroTime"
TJOPEN_FETCHHEROTIME_FIELD.full_name = ".pb.TJopen.FetchHeroTime"
TJOPEN_FETCHHEROTIME_FIELD.number = 1
TJOPEN_FETCHHEROTIME_FIELD.index = 0
TJOPEN_FETCHHEROTIME_FIELD.label = 1
TJOPEN_FETCHHEROTIME_FIELD.has_default_value = false
TJOPEN_FETCHHEROTIME_FIELD.default_value = nil
TJOPEN_FETCHHEROTIME_FIELD.type = 5
TJOPEN_FETCHHEROTIME_FIELD.cpp_type = 1
TJOPEN_FETCHEQUIPTIME_FIELD.name = "FetchEquipTime"
TJOPEN_FETCHEQUIPTIME_FIELD.full_name = ".pb.TJopen.FetchEquipTime"
TJOPEN_FETCHEQUIPTIME_FIELD.number = 2
TJOPEN_FETCHEQUIPTIME_FIELD.index = 1
TJOPEN_FETCHEQUIPTIME_FIELD.label = 1
TJOPEN_FETCHEQUIPTIME_FIELD.has_default_value = false
TJOPEN_FETCHEQUIPTIME_FIELD.default_value = nil
TJOPEN_FETCHEQUIPTIME_FIELD.type = 5
TJOPEN_FETCHEQUIPTIME_FIELD.cpp_type = 1
TJOPEN.file_name = jopen_pb
TJOPEN.name = "TJopen"
TJOPEN.full_name = ".pb.TJopen"
TJOPEN.nested_types = {}
TJOPEN.enum_types = {}
TJOPEN.fields = {TJOPEN_FETCHHEROTIME_FIELD, TJOPEN_FETCHEQUIPTIME_FIELD}
TJOPEN.is_extendable = false
TJOPEN.extensions = {}
TJopen = protobuf.Message(TJOPEN)
return _ENV
