local protobuf = require("net.protobuf.protobuf")
local build_pb = require("net.protobuflua.build_pb")
local notes_pb = {}
_ENV = notes_pb
TNOTESHEROLIKEARG = protobuf.Descriptor()
local TNOTESHEROLIKEARG_HTID_FIELD = protobuf.FieldDescriptor()
TNOTESINFO = protobuf.Descriptor()
local TNOTESINFO_NAME_FIELD = protobuf.FieldDescriptor()
local TNOTESINFO_BUILDEDINFO_FIELD = protobuf.FieldDescriptor()
local TNOTESINFO_COUNT_FIELD = protobuf.FieldDescriptor()
local TNOTESINFO_HEAD_FIELD = protobuf.FieldDescriptor()
local TNOTESINFO_UID_FIELD = protobuf.FieldDescriptor()
TNOTESLISTRET = protobuf.Descriptor()
local TNOTESLISTRET_LIST_FIELD = protobuf.FieldDescriptor()
TNOTESHEROLIKEARG_HTID_FIELD.name = "Htid"
TNOTESHEROLIKEARG_HTID_FIELD.full_name = ".pb.TNotesHeroLikeArg.Htid"
TNOTESHEROLIKEARG_HTID_FIELD.number = 1
TNOTESHEROLIKEARG_HTID_FIELD.index = 0
TNOTESHEROLIKEARG_HTID_FIELD.label = 1
TNOTESHEROLIKEARG_HTID_FIELD.has_default_value = false
TNOTESHEROLIKEARG_HTID_FIELD.default_value = nil
TNOTESHEROLIKEARG_HTID_FIELD.type = 5
TNOTESHEROLIKEARG_HTID_FIELD.cpp_type = 1
TNOTESHEROLIKEARG.file_name = notes_pb
TNOTESHEROLIKEARG.name = "TNotesHeroLikeArg"
TNOTESHEROLIKEARG.full_name = ".pb.TNotesHeroLikeArg"
TNOTESHEROLIKEARG.nested_types = {}
TNOTESHEROLIKEARG.enum_types = {}
TNOTESHEROLIKEARG.fields = {TNOTESHEROLIKEARG_HTID_FIELD}
TNOTESHEROLIKEARG.is_extendable = false
TNOTESHEROLIKEARG.extensions = {}
TNOTESINFO_NAME_FIELD.name = "Name"
TNOTESINFO_NAME_FIELD.full_name = ".pb.TNotesInfo.Name"
TNOTESINFO_NAME_FIELD.number = 1
TNOTESINFO_NAME_FIELD.index = 0
TNOTESINFO_NAME_FIELD.label = 1
TNOTESINFO_NAME_FIELD.has_default_value = false
TNOTESINFO_NAME_FIELD.default_value = nil
TNOTESINFO_NAME_FIELD.type = 9
TNOTESINFO_NAME_FIELD.cpp_type = 9
TNOTESINFO_BUILDEDINFO_FIELD.name = "BuildedInfo"
TNOTESINFO_BUILDEDINFO_FIELD.full_name = ".pb.TNotesInfo.BuildedInfo"
TNOTESINFO_BUILDEDINFO_FIELD.number = 2
TNOTESINFO_BUILDEDINFO_FIELD.index = 1
TNOTESINFO_BUILDEDINFO_FIELD.label = 1
TNOTESINFO_BUILDEDINFO_FIELD.has_default_value = false
TNOTESINFO_BUILDEDINFO_FIELD.default_value = nil
TNOTESINFO_BUILDEDINFO_FIELD.message_type = build_pb.TFORMULA
TNOTESINFO_BUILDEDINFO_FIELD.type = 11
TNOTESINFO_BUILDEDINFO_FIELD.cpp_type = 10
TNOTESINFO_COUNT_FIELD.name = "Count"
TNOTESINFO_COUNT_FIELD.full_name = ".pb.TNotesInfo.Count"
TNOTESINFO_COUNT_FIELD.number = 3
TNOTESINFO_COUNT_FIELD.index = 2
TNOTESINFO_COUNT_FIELD.label = 1
TNOTESINFO_COUNT_FIELD.has_default_value = false
TNOTESINFO_COUNT_FIELD.default_value = nil
TNOTESINFO_COUNT_FIELD.type = 5
TNOTESINFO_COUNT_FIELD.cpp_type = 1
TNOTESINFO_HEAD_FIELD.name = "Head"
TNOTESINFO_HEAD_FIELD.full_name = ".pb.TNotesInfo.Head"
TNOTESINFO_HEAD_FIELD.number = 4
TNOTESINFO_HEAD_FIELD.index = 3
TNOTESINFO_HEAD_FIELD.label = 1
TNOTESINFO_HEAD_FIELD.has_default_value = false
TNOTESINFO_HEAD_FIELD.default_value = nil
TNOTESINFO_HEAD_FIELD.type = 5
TNOTESINFO_HEAD_FIELD.cpp_type = 1
TNOTESINFO_UID_FIELD.name = "Uid"
TNOTESINFO_UID_FIELD.full_name = ".pb.TNotesInfo.Uid"
TNOTESINFO_UID_FIELD.number = 5
TNOTESINFO_UID_FIELD.index = 4
TNOTESINFO_UID_FIELD.label = 1
TNOTESINFO_UID_FIELD.has_default_value = false
TNOTESINFO_UID_FIELD.default_value = nil
TNOTESINFO_UID_FIELD.type = 4
TNOTESINFO_UID_FIELD.cpp_type = 4
TNOTESINFO.file_name = notes_pb
TNOTESINFO.name = "TNotesInfo"
TNOTESINFO.full_name = ".pb.TNotesInfo"
TNOTESINFO.nested_types = {}
TNOTESINFO.enum_types = {}
TNOTESINFO.fields = {
  TNOTESINFO_NAME_FIELD,
  TNOTESINFO_BUILDEDINFO_FIELD,
  TNOTESINFO_COUNT_FIELD,
  TNOTESINFO_HEAD_FIELD,
  TNOTESINFO_UID_FIELD
}
TNOTESINFO.is_extendable = false
TNOTESINFO.extensions = {}
TNOTESLISTRET_LIST_FIELD.name = "List"
TNOTESLISTRET_LIST_FIELD.full_name = ".pb.TNotesListRet.List"
TNOTESLISTRET_LIST_FIELD.number = 1
TNOTESLISTRET_LIST_FIELD.index = 0
TNOTESLISTRET_LIST_FIELD.label = 3
TNOTESLISTRET_LIST_FIELD.has_default_value = false
TNOTESLISTRET_LIST_FIELD.default_value = {}
TNOTESLISTRET_LIST_FIELD.message_type = TNOTESINFO
TNOTESLISTRET_LIST_FIELD.type = 11
TNOTESLISTRET_LIST_FIELD.cpp_type = 10
TNOTESLISTRET.file_name = notes_pb
TNOTESLISTRET.name = "TNotesListRet"
TNOTESLISTRET.full_name = ".pb.TNotesListRet"
TNOTESLISTRET.nested_types = {}
TNOTESLISTRET.enum_types = {}
TNOTESLISTRET.fields = {TNOTESLISTRET_LIST_FIELD}
TNOTESLISTRET.is_extendable = false
TNOTESLISTRET.extensions = {}
TNotesHeroLikeArg = protobuf.Message(TNOTESHEROLIKEARG)
TNotesInfo = protobuf.Message(TNOTESINFO)
TNotesListRet = protobuf.Message(TNOTESLISTRET)
return _ENV
