local protobuf = require("net.protobuf.protobuf")
local presetfleet_pb = {}
_ENV = presetfleet_pb
TPRESETFLEET = protobuf.Descriptor()
local TPRESETFLEET_NAME_FIELD = protobuf.FieldDescriptor()
local TPRESETFLEET_HEROLIST_FIELD = protobuf.FieldDescriptor()
local TPRESETFLEET_MODEID_FIELD = protobuf.FieldDescriptor()
local TPRESETFLEET_STRATEGYID_FIELD = protobuf.FieldDescriptor()
local TPRESETFLEET_EXHEROLIST_FIELD = protobuf.FieldDescriptor()
TSELFPRESETFLEETS = protobuf.Descriptor()
local TSELFPRESETFLEETS_PRESETFLEET_FIELD = protobuf.FieldDescriptor()
local TSELFPRESETFLEETS_NAMENUM_FIELD = protobuf.FieldDescriptor()
local TSELFPRESETFLEETS_REDDOT_FIELD = protobuf.FieldDescriptor()
TPRESETFLEET_NAME_FIELD.name = "Name"
TPRESETFLEET_NAME_FIELD.full_name = ".pb.TPresetFleet.Name"
TPRESETFLEET_NAME_FIELD.number = 1
TPRESETFLEET_NAME_FIELD.index = 0
TPRESETFLEET_NAME_FIELD.label = 1
TPRESETFLEET_NAME_FIELD.has_default_value = false
TPRESETFLEET_NAME_FIELD.default_value = nil
TPRESETFLEET_NAME_FIELD.type = 9
TPRESETFLEET_NAME_FIELD.cpp_type = 9
TPRESETFLEET_HEROLIST_FIELD.name = "heroList"
TPRESETFLEET_HEROLIST_FIELD.full_name = ".pb.TPresetFleet.heroList"
TPRESETFLEET_HEROLIST_FIELD.number = 2
TPRESETFLEET_HEROLIST_FIELD.index = 1
TPRESETFLEET_HEROLIST_FIELD.label = 3
TPRESETFLEET_HEROLIST_FIELD.has_default_value = false
TPRESETFLEET_HEROLIST_FIELD.default_value = {}
TPRESETFLEET_HEROLIST_FIELD.type = 13
TPRESETFLEET_HEROLIST_FIELD.cpp_type = 3
TPRESETFLEET_MODEID_FIELD.name = "modeId"
TPRESETFLEET_MODEID_FIELD.full_name = ".pb.TPresetFleet.modeId"
TPRESETFLEET_MODEID_FIELD.number = 3
TPRESETFLEET_MODEID_FIELD.index = 2
TPRESETFLEET_MODEID_FIELD.label = 1
TPRESETFLEET_MODEID_FIELD.has_default_value = false
TPRESETFLEET_MODEID_FIELD.default_value = nil
TPRESETFLEET_MODEID_FIELD.type = 5
TPRESETFLEET_MODEID_FIELD.cpp_type = 1
TPRESETFLEET_STRATEGYID_FIELD.name = "strategyId"
TPRESETFLEET_STRATEGYID_FIELD.full_name = ".pb.TPresetFleet.strategyId"
TPRESETFLEET_STRATEGYID_FIELD.number = 4
TPRESETFLEET_STRATEGYID_FIELD.index = 3
TPRESETFLEET_STRATEGYID_FIELD.label = 1
TPRESETFLEET_STRATEGYID_FIELD.has_default_value = false
TPRESETFLEET_STRATEGYID_FIELD.default_value = nil
TPRESETFLEET_STRATEGYID_FIELD.type = 5
TPRESETFLEET_STRATEGYID_FIELD.cpp_type = 1
TPRESETFLEET_EXHEROLIST_FIELD.name = "exHeroList"
TPRESETFLEET_EXHEROLIST_FIELD.full_name = ".pb.TPresetFleet.exHeroList"
TPRESETFLEET_EXHEROLIST_FIELD.number = 5
TPRESETFLEET_EXHEROLIST_FIELD.index = 4
TPRESETFLEET_EXHEROLIST_FIELD.label = 3
TPRESETFLEET_EXHEROLIST_FIELD.has_default_value = false
TPRESETFLEET_EXHEROLIST_FIELD.default_value = {}
TPRESETFLEET_EXHEROLIST_FIELD.type = 13
TPRESETFLEET_EXHEROLIST_FIELD.cpp_type = 3
TPRESETFLEET.file_name = presetfleet_pb
TPRESETFLEET.name = "TPresetFleet"
TPRESETFLEET.full_name = ".pb.TPresetFleet"
TPRESETFLEET.nested_types = {}
TPRESETFLEET.enum_types = {}
TPRESETFLEET.fields = {
  TPRESETFLEET_NAME_FIELD,
  TPRESETFLEET_HEROLIST_FIELD,
  TPRESETFLEET_MODEID_FIELD,
  TPRESETFLEET_STRATEGYID_FIELD,
  TPRESETFLEET_EXHEROLIST_FIELD
}
TPRESETFLEET.is_extendable = false
TPRESETFLEET.extensions = {}
TSELFPRESETFLEETS_PRESETFLEET_FIELD.name = "presetfleet"
TSELFPRESETFLEETS_PRESETFLEET_FIELD.full_name = ".pb.TSelfPresetFleets.presetfleet"
TSELFPRESETFLEETS_PRESETFLEET_FIELD.number = 1
TSELFPRESETFLEETS_PRESETFLEET_FIELD.index = 0
TSELFPRESETFLEETS_PRESETFLEET_FIELD.label = 3
TSELFPRESETFLEETS_PRESETFLEET_FIELD.has_default_value = false
TSELFPRESETFLEETS_PRESETFLEET_FIELD.default_value = {}
TSELFPRESETFLEETS_PRESETFLEET_FIELD.message_type = TPRESETFLEET
TSELFPRESETFLEETS_PRESETFLEET_FIELD.type = 11
TSELFPRESETFLEETS_PRESETFLEET_FIELD.cpp_type = 10
TSELFPRESETFLEETS_NAMENUM_FIELD.name = "NameNum"
TSELFPRESETFLEETS_NAMENUM_FIELD.full_name = ".pb.TSelfPresetFleets.NameNum"
TSELFPRESETFLEETS_NAMENUM_FIELD.number = 2
TSELFPRESETFLEETS_NAMENUM_FIELD.index = 1
TSELFPRESETFLEETS_NAMENUM_FIELD.label = 1
TSELFPRESETFLEETS_NAMENUM_FIELD.has_default_value = false
TSELFPRESETFLEETS_NAMENUM_FIELD.default_value = nil
TSELFPRESETFLEETS_NAMENUM_FIELD.type = 13
TSELFPRESETFLEETS_NAMENUM_FIELD.cpp_type = 3
TSELFPRESETFLEETS_REDDOT_FIELD.name = "redDot"
TSELFPRESETFLEETS_REDDOT_FIELD.full_name = ".pb.TSelfPresetFleets.redDot"
TSELFPRESETFLEETS_REDDOT_FIELD.number = 3
TSELFPRESETFLEETS_REDDOT_FIELD.index = 2
TSELFPRESETFLEETS_REDDOT_FIELD.label = 1
TSELFPRESETFLEETS_REDDOT_FIELD.has_default_value = false
TSELFPRESETFLEETS_REDDOT_FIELD.default_value = nil
TSELFPRESETFLEETS_REDDOT_FIELD.type = 13
TSELFPRESETFLEETS_REDDOT_FIELD.cpp_type = 3
TSELFPRESETFLEETS.file_name = presetfleet_pb
TSELFPRESETFLEETS.name = "TSelfPresetFleets"
TSELFPRESETFLEETS.full_name = ".pb.TSelfPresetFleets"
TSELFPRESETFLEETS.nested_types = {}
TSELFPRESETFLEETS.enum_types = {}
TSELFPRESETFLEETS.fields = {
  TSELFPRESETFLEETS_PRESETFLEET_FIELD,
  TSELFPRESETFLEETS_NAMENUM_FIELD,
  TSELFPRESETFLEETS_REDDOT_FIELD
}
TSELFPRESETFLEETS.is_extendable = false
TSELFPRESETFLEETS.extensions = {}
TPresetFleet = protobuf.Message(TPRESETFLEET)
TSelfPresetFleets = protobuf.Message(TSELFPRESETFLEETS)
return _ENV
