local protobuf = require("net.protobuf.protobuf")
local prize_pb = {}
_ENV = prize_pb
TOBJ = protobuf.Descriptor()
local TOBJ_TYPE_FIELD = protobuf.FieldDescriptor()
local TOBJ_ID_FIELD = protobuf.FieldDescriptor()
local TOBJ_NUM_FIELD = protobuf.FieldDescriptor()
TPRIZE = protobuf.Descriptor()
local TPRIZE_ID_FIELD = protobuf.FieldDescriptor()
local TPRIZE_TEMPLATEID_FIELD = protobuf.FieldDescriptor()
local TPRIZE_RECEIVETIME_FIELD = protobuf.FieldDescriptor()
local TPRIZE_REWARDLIST_FIELD = protobuf.FieldDescriptor()
local TPRIZE_TYPE_FIELD = protobuf.FieldDescriptor()
local TPRIZE_PARAMS_FIELD = protobuf.FieldDescriptor()
local TPRIZE_OBJLIST_FIELD = protobuf.FieldDescriptor()
TPRIZEPARAM = protobuf.Descriptor()
local TPRIZEPARAM_TYPE_FIELD = protobuf.FieldDescriptor()
local TPRIZEPARAM_DATA_FIELD = protobuf.FieldDescriptor()
TGETPRIZEINFOARG = protobuf.Descriptor()
local TGETPRIZEINFOARG_START_FIELD = protobuf.FieldDescriptor()
local TGETPRIZEINFOARG_NUM_FIELD = protobuf.FieldDescriptor()
TPRIZEINFO = protobuf.Descriptor()
local TPRIZEINFO_PRIZELIST_FIELD = protobuf.FieldDescriptor()
local TPRIZEINFO_DELPRIZE_FIELD = protobuf.FieldDescriptor()
local TPRIZEINFO_HAVEUNGETPRIZE_FIELD = protobuf.FieldDescriptor()
TACCEPTPRIZEARG = protobuf.Descriptor()
local TACCEPTPRIZEARG_PRIZELIST_FIELD = protobuf.FieldDescriptor()
TACCEPTPRIZERET = protobuf.Descriptor()
TSIMPLEPRIZE = protobuf.Descriptor()
local TSIMPLEPRIZE_TYPE_FIELD = protobuf.FieldDescriptor()
local TSIMPLEPRIZE_ID_FIELD = protobuf.FieldDescriptor()
TOBJ_TYPE_FIELD.name = "Type"
TOBJ_TYPE_FIELD.full_name = ".pb.TObj.Type"
TOBJ_TYPE_FIELD.number = 1
TOBJ_TYPE_FIELD.index = 0
TOBJ_TYPE_FIELD.label = 1
TOBJ_TYPE_FIELD.has_default_value = false
TOBJ_TYPE_FIELD.default_value = nil
TOBJ_TYPE_FIELD.type = 5
TOBJ_TYPE_FIELD.cpp_type = 1
TOBJ_ID_FIELD.name = "Id"
TOBJ_ID_FIELD.full_name = ".pb.TObj.Id"
TOBJ_ID_FIELD.number = 2
TOBJ_ID_FIELD.index = 1
TOBJ_ID_FIELD.label = 1
TOBJ_ID_FIELD.has_default_value = false
TOBJ_ID_FIELD.default_value = nil
TOBJ_ID_FIELD.type = 5
TOBJ_ID_FIELD.cpp_type = 1
TOBJ_NUM_FIELD.name = "Num"
TOBJ_NUM_FIELD.full_name = ".pb.TObj.Num"
TOBJ_NUM_FIELD.number = 3
TOBJ_NUM_FIELD.index = 2
TOBJ_NUM_FIELD.label = 1
TOBJ_NUM_FIELD.has_default_value = false
TOBJ_NUM_FIELD.default_value = nil
TOBJ_NUM_FIELD.type = 5
TOBJ_NUM_FIELD.cpp_type = 1
TOBJ.file_name = prize_pb
TOBJ.name = "TObj"
TOBJ.full_name = ".pb.TObj"
TOBJ.nested_types = {}
TOBJ.enum_types = {}
TOBJ.fields = {
  TOBJ_TYPE_FIELD,
  TOBJ_ID_FIELD,
  TOBJ_NUM_FIELD
}
TOBJ.is_extendable = false
TOBJ.extensions = {}
TPRIZE_ID_FIELD.name = "Id"
TPRIZE_ID_FIELD.full_name = ".pb.TPrize.Id"
TPRIZE_ID_FIELD.number = 1
TPRIZE_ID_FIELD.index = 0
TPRIZE_ID_FIELD.label = 1
TPRIZE_ID_FIELD.has_default_value = false
TPRIZE_ID_FIELD.default_value = nil
TPRIZE_ID_FIELD.type = 5
TPRIZE_ID_FIELD.cpp_type = 1
TPRIZE_TEMPLATEID_FIELD.name = "TemplateId"
TPRIZE_TEMPLATEID_FIELD.full_name = ".pb.TPrize.TemplateId"
TPRIZE_TEMPLATEID_FIELD.number = 2
TPRIZE_TEMPLATEID_FIELD.index = 1
TPRIZE_TEMPLATEID_FIELD.label = 1
TPRIZE_TEMPLATEID_FIELD.has_default_value = false
TPRIZE_TEMPLATEID_FIELD.default_value = nil
TPRIZE_TEMPLATEID_FIELD.type = 5
TPRIZE_TEMPLATEID_FIELD.cpp_type = 1
TPRIZE_RECEIVETIME_FIELD.name = "ReceiveTime"
TPRIZE_RECEIVETIME_FIELD.full_name = ".pb.TPrize.ReceiveTime"
TPRIZE_RECEIVETIME_FIELD.number = 3
TPRIZE_RECEIVETIME_FIELD.index = 2
TPRIZE_RECEIVETIME_FIELD.label = 1
TPRIZE_RECEIVETIME_FIELD.has_default_value = false
TPRIZE_RECEIVETIME_FIELD.default_value = nil
TPRIZE_RECEIVETIME_FIELD.type = 5
TPRIZE_RECEIVETIME_FIELD.cpp_type = 1
TPRIZE_REWARDLIST_FIELD.name = "RewardList"
TPRIZE_REWARDLIST_FIELD.full_name = ".pb.TPrize.RewardList"
TPRIZE_REWARDLIST_FIELD.number = 4
TPRIZE_REWARDLIST_FIELD.index = 3
TPRIZE_REWARDLIST_FIELD.label = 3
TPRIZE_REWARDLIST_FIELD.has_default_value = false
TPRIZE_REWARDLIST_FIELD.default_value = {}
TPRIZE_REWARDLIST_FIELD.type = 5
TPRIZE_REWARDLIST_FIELD.cpp_type = 1
TPRIZE_TYPE_FIELD.name = "Type"
TPRIZE_TYPE_FIELD.full_name = ".pb.TPrize.Type"
TPRIZE_TYPE_FIELD.number = 5
TPRIZE_TYPE_FIELD.index = 4
TPRIZE_TYPE_FIELD.label = 1
TPRIZE_TYPE_FIELD.has_default_value = false
TPRIZE_TYPE_FIELD.default_value = nil
TPRIZE_TYPE_FIELD.type = 5
TPRIZE_TYPE_FIELD.cpp_type = 1
TPRIZE_PARAMS_FIELD.name = "Params"
TPRIZE_PARAMS_FIELD.full_name = ".pb.TPrize.Params"
TPRIZE_PARAMS_FIELD.number = 6
TPRIZE_PARAMS_FIELD.index = 5
TPRIZE_PARAMS_FIELD.label = 3
TPRIZE_PARAMS_FIELD.has_default_value = false
TPRIZE_PARAMS_FIELD.default_value = {}
TPRIZE_PARAMS_FIELD.message_type = TPRIZEPARAM
TPRIZE_PARAMS_FIELD.type = 11
TPRIZE_PARAMS_FIELD.cpp_type = 10
TPRIZE_OBJLIST_FIELD.name = "ObjList"
TPRIZE_OBJLIST_FIELD.full_name = ".pb.TPrize.ObjList"
TPRIZE_OBJLIST_FIELD.number = 7
TPRIZE_OBJLIST_FIELD.index = 6
TPRIZE_OBJLIST_FIELD.label = 3
TPRIZE_OBJLIST_FIELD.has_default_value = false
TPRIZE_OBJLIST_FIELD.default_value = {}
TPRIZE_OBJLIST_FIELD.message_type = TOBJ
TPRIZE_OBJLIST_FIELD.type = 11
TPRIZE_OBJLIST_FIELD.cpp_type = 10
TPRIZE.file_name = prize_pb
TPRIZE.name = "TPrize"
TPRIZE.full_name = ".pb.TPrize"
TPRIZE.nested_types = {}
TPRIZE.enum_types = {}
TPRIZE.fields = {
  TPRIZE_ID_FIELD,
  TPRIZE_TEMPLATEID_FIELD,
  TPRIZE_RECEIVETIME_FIELD,
  TPRIZE_REWARDLIST_FIELD,
  TPRIZE_TYPE_FIELD,
  TPRIZE_PARAMS_FIELD,
  TPRIZE_OBJLIST_FIELD
}
TPRIZE.is_extendable = false
TPRIZE.extensions = {}
TPRIZEPARAM_TYPE_FIELD.name = "Type"
TPRIZEPARAM_TYPE_FIELD.full_name = ".pb.TPrizeParam.Type"
TPRIZEPARAM_TYPE_FIELD.number = 1
TPRIZEPARAM_TYPE_FIELD.index = 0
TPRIZEPARAM_TYPE_FIELD.label = 1
TPRIZEPARAM_TYPE_FIELD.has_default_value = false
TPRIZEPARAM_TYPE_FIELD.default_value = nil
TPRIZEPARAM_TYPE_FIELD.type = 5
TPRIZEPARAM_TYPE_FIELD.cpp_type = 1
TPRIZEPARAM_DATA_FIELD.name = "Data"
TPRIZEPARAM_DATA_FIELD.full_name = ".pb.TPrizeParam.Data"
TPRIZEPARAM_DATA_FIELD.number = 2
TPRIZEPARAM_DATA_FIELD.index = 1
TPRIZEPARAM_DATA_FIELD.label = 1
TPRIZEPARAM_DATA_FIELD.has_default_value = false
TPRIZEPARAM_DATA_FIELD.default_value = nil
TPRIZEPARAM_DATA_FIELD.type = 9
TPRIZEPARAM_DATA_FIELD.cpp_type = 9
TPRIZEPARAM.file_name = prize_pb
TPRIZEPARAM.name = "TPrizeParam"
TPRIZEPARAM.full_name = ".pb.TPrizeParam"
TPRIZEPARAM.nested_types = {}
TPRIZEPARAM.enum_types = {}
TPRIZEPARAM.fields = {TPRIZEPARAM_TYPE_FIELD, TPRIZEPARAM_DATA_FIELD}
TPRIZEPARAM.is_extendable = false
TPRIZEPARAM.extensions = {}
TGETPRIZEINFOARG_START_FIELD.name = "Start"
TGETPRIZEINFOARG_START_FIELD.full_name = ".pb.TGetPrizeInfoArg.Start"
TGETPRIZEINFOARG_START_FIELD.number = 1
TGETPRIZEINFOARG_START_FIELD.index = 0
TGETPRIZEINFOARG_START_FIELD.label = 1
TGETPRIZEINFOARG_START_FIELD.has_default_value = false
TGETPRIZEINFOARG_START_FIELD.default_value = nil
TGETPRIZEINFOARG_START_FIELD.type = 5
TGETPRIZEINFOARG_START_FIELD.cpp_type = 1
TGETPRIZEINFOARG_NUM_FIELD.name = "Num"
TGETPRIZEINFOARG_NUM_FIELD.full_name = ".pb.TGetPrizeInfoArg.Num"
TGETPRIZEINFOARG_NUM_FIELD.number = 2
TGETPRIZEINFOARG_NUM_FIELD.index = 1
TGETPRIZEINFOARG_NUM_FIELD.label = 1
TGETPRIZEINFOARG_NUM_FIELD.has_default_value = false
TGETPRIZEINFOARG_NUM_FIELD.default_value = nil
TGETPRIZEINFOARG_NUM_FIELD.type = 5
TGETPRIZEINFOARG_NUM_FIELD.cpp_type = 1
TGETPRIZEINFOARG.file_name = prize_pb
TGETPRIZEINFOARG.name = "TGetPrizeInfoArg"
TGETPRIZEINFOARG.full_name = ".pb.TGetPrizeInfoArg"
TGETPRIZEINFOARG.nested_types = {}
TGETPRIZEINFOARG.enum_types = {}
TGETPRIZEINFOARG.fields = {TGETPRIZEINFOARG_START_FIELD, TGETPRIZEINFOARG_NUM_FIELD}
TGETPRIZEINFOARG.is_extendable = false
TGETPRIZEINFOARG.extensions = {}
TPRIZEINFO_PRIZELIST_FIELD.name = "PrizeList"
TPRIZEINFO_PRIZELIST_FIELD.full_name = ".pb.TPrizeInfo.PrizeList"
TPRIZEINFO_PRIZELIST_FIELD.number = 1
TPRIZEINFO_PRIZELIST_FIELD.index = 0
TPRIZEINFO_PRIZELIST_FIELD.label = 3
TPRIZEINFO_PRIZELIST_FIELD.has_default_value = false
TPRIZEINFO_PRIZELIST_FIELD.default_value = {}
TPRIZEINFO_PRIZELIST_FIELD.message_type = TPRIZE
TPRIZEINFO_PRIZELIST_FIELD.type = 11
TPRIZEINFO_PRIZELIST_FIELD.cpp_type = 10
TPRIZEINFO_DELPRIZE_FIELD.name = "DelPrize"
TPRIZEINFO_DELPRIZE_FIELD.full_name = ".pb.TPrizeInfo.DelPrize"
TPRIZEINFO_DELPRIZE_FIELD.number = 2
TPRIZEINFO_DELPRIZE_FIELD.index = 1
TPRIZEINFO_DELPRIZE_FIELD.label = 3
TPRIZEINFO_DELPRIZE_FIELD.has_default_value = false
TPRIZEINFO_DELPRIZE_FIELD.default_value = {}
TPRIZEINFO_DELPRIZE_FIELD.message_type = TSIMPLEPRIZE
TPRIZEINFO_DELPRIZE_FIELD.type = 11
TPRIZEINFO_DELPRIZE_FIELD.cpp_type = 10
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.name = "HaveUngetPrize"
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.full_name = ".pb.TPrizeInfo.HaveUngetPrize"
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.number = 3
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.index = 2
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.label = 1
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.has_default_value = false
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.default_value = nil
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.type = 5
TPRIZEINFO_HAVEUNGETPRIZE_FIELD.cpp_type = 1
TPRIZEINFO.file_name = prize_pb
TPRIZEINFO.name = "TPrizeInfo"
TPRIZEINFO.full_name = ".pb.TPrizeInfo"
TPRIZEINFO.nested_types = {}
TPRIZEINFO.enum_types = {}
TPRIZEINFO.fields = {
  TPRIZEINFO_PRIZELIST_FIELD,
  TPRIZEINFO_DELPRIZE_FIELD,
  TPRIZEINFO_HAVEUNGETPRIZE_FIELD
}
TPRIZEINFO.is_extendable = false
TPRIZEINFO.extensions = {}
TACCEPTPRIZEARG_PRIZELIST_FIELD.name = "PrizeList"
TACCEPTPRIZEARG_PRIZELIST_FIELD.full_name = ".pb.TAcceptPrizeArg.PrizeList"
TACCEPTPRIZEARG_PRIZELIST_FIELD.number = 1
TACCEPTPRIZEARG_PRIZELIST_FIELD.index = 0
TACCEPTPRIZEARG_PRIZELIST_FIELD.label = 3
TACCEPTPRIZEARG_PRIZELIST_FIELD.has_default_value = false
TACCEPTPRIZEARG_PRIZELIST_FIELD.default_value = {}
TACCEPTPRIZEARG_PRIZELIST_FIELD.message_type = TSIMPLEPRIZE
TACCEPTPRIZEARG_PRIZELIST_FIELD.type = 11
TACCEPTPRIZEARG_PRIZELIST_FIELD.cpp_type = 10
TACCEPTPRIZEARG.file_name = prize_pb
TACCEPTPRIZEARG.name = "TAcceptPrizeArg"
TACCEPTPRIZEARG.full_name = ".pb.TAcceptPrizeArg"
TACCEPTPRIZEARG.nested_types = {}
TACCEPTPRIZEARG.enum_types = {}
TACCEPTPRIZEARG.fields = {TACCEPTPRIZEARG_PRIZELIST_FIELD}
TACCEPTPRIZEARG.is_extendable = false
TACCEPTPRIZEARG.extensions = {}
TACCEPTPRIZERET.file_name = prize_pb
TACCEPTPRIZERET.name = "TAcceptPrizeRet"
TACCEPTPRIZERET.full_name = ".pb.TAcceptPrizeRet"
TACCEPTPRIZERET.nested_types = {}
TACCEPTPRIZERET.enum_types = {}
TACCEPTPRIZERET.fields = {}
TACCEPTPRIZERET.is_extendable = false
TACCEPTPRIZERET.extensions = {}
TSIMPLEPRIZE_TYPE_FIELD.name = "Type"
TSIMPLEPRIZE_TYPE_FIELD.full_name = ".pb.TSimplePrize.Type"
TSIMPLEPRIZE_TYPE_FIELD.number = 1
TSIMPLEPRIZE_TYPE_FIELD.index = 0
TSIMPLEPRIZE_TYPE_FIELD.label = 1
TSIMPLEPRIZE_TYPE_FIELD.has_default_value = false
TSIMPLEPRIZE_TYPE_FIELD.default_value = nil
TSIMPLEPRIZE_TYPE_FIELD.type = 5
TSIMPLEPRIZE_TYPE_FIELD.cpp_type = 1
TSIMPLEPRIZE_ID_FIELD.name = "Id"
TSIMPLEPRIZE_ID_FIELD.full_name = ".pb.TSimplePrize.Id"
TSIMPLEPRIZE_ID_FIELD.number = 2
TSIMPLEPRIZE_ID_FIELD.index = 1
TSIMPLEPRIZE_ID_FIELD.label = 1
TSIMPLEPRIZE_ID_FIELD.has_default_value = false
TSIMPLEPRIZE_ID_FIELD.default_value = nil
TSIMPLEPRIZE_ID_FIELD.type = 5
TSIMPLEPRIZE_ID_FIELD.cpp_type = 1
TSIMPLEPRIZE.file_name = prize_pb
TSIMPLEPRIZE.name = "TSimplePrize"
TSIMPLEPRIZE.full_name = ".pb.TSimplePrize"
TSIMPLEPRIZE.nested_types = {}
TSIMPLEPRIZE.enum_types = {}
TSIMPLEPRIZE.fields = {TSIMPLEPRIZE_TYPE_FIELD, TSIMPLEPRIZE_ID_FIELD}
TSIMPLEPRIZE.is_extendable = false
TSIMPLEPRIZE.extensions = {}
TAcceptPrizeArg = protobuf.Message(TACCEPTPRIZEARG)
TAcceptPrizeRet = protobuf.Message(TACCEPTPRIZERET)
TGetPrizeInfoArg = protobuf.Message(TGETPRIZEINFOARG)
TObj = protobuf.Message(TOBJ)
TPrize = protobuf.Message(TPRIZE)
TPrizeInfo = protobuf.Message(TPRIZEINFO)
TPrizeParam = protobuf.Message(TPRIZEPARAM)
TSimplePrize = protobuf.Message(TSIMPLEPRIZE)
return _ENV
