local protobuf = require("net.protobuf.protobuf")
local stlog_pb = {}
_ENV = stlog_pb
TSTLOGARG = protobuf.Descriptor()
local TSTLOGARG_EVENTID_FIELD = protobuf.FieldDescriptor()
local TSTLOGARG_EVENTVALUE_FIELD = protobuf.FieldDescriptor()
TSTLOGARG_EVENTID_FIELD.name = "EventId"
TSTLOGARG_EVENTID_FIELD.full_name = ".pb.TStLogArg.EventId"
TSTLOGARG_EVENTID_FIELD.number = 1
TSTLOGARG_EVENTID_FIELD.index = 0
TSTLOGARG_EVENTID_FIELD.label = 1
TSTLOGARG_EVENTID_FIELD.has_default_value = false
TSTLOGARG_EVENTID_FIELD.default_value = nil
TSTLOGARG_EVENTID_FIELD.type = 9
TSTLOGARG_EVENTID_FIELD.cpp_type = 9
TSTLOGARG_EVENTVALUE_FIELD.name = "EventValue"
TSTLOGARG_EVENTVALUE_FIELD.full_name = ".pb.TStLogArg.EventValue"
TSTLOGARG_EVENTVALUE_FIELD.number = 2
TSTLOGARG_EVENTVALUE_FIELD.index = 1
TSTLOGARG_EVENTVALUE_FIELD.label = 1
TSTLOGARG_EVENTVALUE_FIELD.has_default_value = false
TSTLOGARG_EVENTVALUE_FIELD.default_value = nil
TSTLOGARG_EVENTVALUE_FIELD.type = 9
TSTLOGARG_EVENTVALUE_FIELD.cpp_type = 9
TSTLOGARG.file_name = stlog_pb
TSTLOGARG.name = "TStLogArg"
TSTLOGARG.full_name = ".pb.TStLogArg"
TSTLOGARG.nested_types = {}
TSTLOGARG.enum_types = {}
TSTLOGARG.fields = {TSTLOGARG_EVENTID_FIELD, TSTLOGARG_EVENTVALUE_FIELD}
TSTLOGARG.is_extendable = false
TSTLOGARG.extensions = {}
TStLogArg = protobuf.Message(TSTLOGARG)
return _ENV
