local protobuf = require("net.protobuf.protobuf")
local syncJson_pb = {}
_ENV = syncJson_pb
TSYNCJSON = protobuf.Descriptor()
local TSYNCJSON_NAME_FIELD = protobuf.FieldDescriptor()
local TSYNCJSON_CONTENT_FIELD = protobuf.FieldDescriptor()
TSYNCJSON_NAME_FIELD.name = "Name"
TSYNCJSON_NAME_FIELD.full_name = ".pb.TSyncJson.Name"
TSYNCJSON_NAME_FIELD.number = 1
TSYNCJSON_NAME_FIELD.index = 0
TSYNCJSON_NAME_FIELD.label = 1
TSYNCJSON_NAME_FIELD.has_default_value = false
TSYNCJSON_NAME_FIELD.default_value = nil
TSYNCJSON_NAME_FIELD.type = 9
TSYNCJSON_NAME_FIELD.cpp_type = 9
TSYNCJSON_CONTENT_FIELD.name = "Content"
TSYNCJSON_CONTENT_FIELD.full_name = ".pb.TSyncJson.Content"
TSYNCJSON_CONTENT_FIELD.number = 2
TSYNCJSON_CONTENT_FIELD.index = 1
TSYNCJSON_CONTENT_FIELD.label = 1
TSYNCJSON_CONTENT_FIELD.has_default_value = false
TSYNCJSON_CONTENT_FIELD.default_value = nil
TSYNCJSON_CONTENT_FIELD.type = 9
TSYNCJSON_CONTENT_FIELD.cpp_type = 9
TSYNCJSON.file_name = syncJson_pb
TSYNCJSON.name = "TSyncJson"
TSYNCJSON.full_name = ".pb.TSyncJson"
TSYNCJSON.nested_types = {}
TSYNCJSON.enum_types = {}
TSYNCJSON.fields = {TSYNCJSON_NAME_FIELD, TSYNCJSON_CONTENT_FIELD}
TSYNCJSON.is_extendable = false
TSYNCJSON.extensions = {}
TSyncJson = protobuf.Message(TSYNCJSON)
return _ENV
