local protobuf = require("net.protobuf.protobuf")
local vote_pb = {}
_ENV = vote_pb
TVOTE = protobuf.Descriptor()
local TVOTE_MAGAZINEID_FIELD = protobuf.FieldDescriptor()
local TVOTE_VOTELIST_FIELD = protobuf.FieldDescriptor()
TVOTESUB = protobuf.Descriptor()
local TVOTESUB_ID_FIELD = protobuf.FieldDescriptor()
local TVOTESUB_NUM_FIELD = protobuf.FieldDescriptor()
TVOTE_MAGAZINEID_FIELD.name = "MagazineId"
TVOTE_MAGAZINEID_FIELD.full_name = ".pb.TVote.MagazineId"
TVOTE_MAGAZINEID_FIELD.number = 1
TVOTE_MAGAZINEID_FIELD.index = 0
TVOTE_MAGAZINEID_FIELD.label = 1
TVOTE_MAGAZINEID_FIELD.has_default_value = false
TVOTE_MAGAZINEID_FIELD.default_value = nil
TVOTE_MAGAZINEID_FIELD.type = 5
TVOTE_MAGAZINEID_FIELD.cpp_type = 1
TVOTE_VOTELIST_FIELD.name = "VoteList"
TVOTE_VOTELIST_FIELD.full_name = ".pb.TVote.VoteList"
TVOTE_VOTELIST_FIELD.number = 2
TVOTE_VOTELIST_FIELD.index = 1
TVOTE_VOTELIST_FIELD.label = 3
TVOTE_VOTELIST_FIELD.has_default_value = false
TVOTE_VOTELIST_FIELD.default_value = {}
TVOTE_VOTELIST_FIELD.message_type = TVOTESUB
TVOTE_VOTELIST_FIELD.type = 11
TVOTE_VOTELIST_FIELD.cpp_type = 10
TVOTE.file_name = vote_pb
TVOTE.name = "TVote"
TVOTE.full_name = ".pb.TVote"
TVOTE.nested_types = {}
TVOTE.enum_types = {}
TVOTE.fields = {TVOTE_MAGAZINEID_FIELD, TVOTE_VOTELIST_FIELD}
TVOTE.is_extendable = false
TVOTE.extensions = {}
TVOTESUB_ID_FIELD.name = "Id"
TVOTESUB_ID_FIELD.full_name = ".pb.TVoteSub.Id"
TVOTESUB_ID_FIELD.number = 1
TVOTESUB_ID_FIELD.index = 0
TVOTESUB_ID_FIELD.label = 1
TVOTESUB_ID_FIELD.has_default_value = false
TVOTESUB_ID_FIELD.default_value = nil
TVOTESUB_ID_FIELD.type = 5
TVOTESUB_ID_FIELD.cpp_type = 1
TVOTESUB_NUM_FIELD.name = "Num"
TVOTESUB_NUM_FIELD.full_name = ".pb.TVoteSub.Num"
TVOTESUB_NUM_FIELD.number = 2
TVOTESUB_NUM_FIELD.index = 1
TVOTESUB_NUM_FIELD.label = 1
TVOTESUB_NUM_FIELD.has_default_value = false
TVOTESUB_NUM_FIELD.default_value = nil
TVOTESUB_NUM_FIELD.type = 5
TVOTESUB_NUM_FIELD.cpp_type = 1
TVOTESUB.file_name = vote_pb
TVOTESUB.name = "TVoteSub"
TVOTESUB.full_name = ".pb.TVoteSub"
TVOTESUB.nested_types = {}
TVOTESUB.enum_types = {}
TVOTESUB.fields = {TVOTESUB_ID_FIELD, TVOTESUB_NUM_FIELD}
TVOTESUB.is_extendable = false
TVOTESUB.extensions = {}
TVote = protobuf.Message(TVOTE)
TVoteSub = protobuf.Message(TVOTESUB)
return _ENV
