local protobuf = require("net.protobuf.protobuf")
local walkdogcopy_pb = {}
_ENV = walkdogcopy_pb
TGETWALKDOGCOPYINFO = protobuf.Descriptor()
local TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD = protobuf.FieldDescriptor()
local TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD = protobuf.FieldDescriptor()
local TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD = protobuf.FieldDescriptor()
local TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD = protobuf.FieldDescriptor()
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.name = "MaxLiveTime"
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.full_name = ".pb.TGetWalkDogCopyInfo.MaxLiveTime"
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.number = 1
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.index = 0
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.label = 1
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.has_default_value = false
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.default_value = nil
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.type = 5
TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD.cpp_type = 1
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.name = "LastUpdateTime"
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.full_name = ".pb.TGetWalkDogCopyInfo.LastUpdateTime"
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.number = 2
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.index = 1
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.label = 1
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.has_default_value = false
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.default_value = nil
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.type = 5
TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD.cpp_type = 1
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.name = "MaxSingleScore"
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.full_name = ".pb.TGetWalkDogCopyInfo.MaxSingleScore"
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.number = 3
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.index = 2
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.label = 1
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.has_default_value = false
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.default_value = nil
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.type = 5
TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD.cpp_type = 1
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.name = "MaxSingleKill"
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.full_name = ".pb.TGetWalkDogCopyInfo.MaxSingleKill"
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.number = 4
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.index = 3
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.label = 1
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.has_default_value = false
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.default_value = nil
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.type = 5
TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD.cpp_type = 1
TGETWALKDOGCOPYINFO.file_name = walkdogcopy_pb
TGETWALKDOGCOPYINFO.name = "TGetWalkDogCopyInfo"
TGETWALKDOGCOPYINFO.full_name = ".pb.TGetWalkDogCopyInfo"
TGETWALKDOGCOPYINFO.nested_types = {}
TGETWALKDOGCOPYINFO.enum_types = {}
TGETWALKDOGCOPYINFO.fields = {
  TGETWALKDOGCOPYINFO_MAXLIVETIME_FIELD,
  TGETWALKDOGCOPYINFO_LASTUPDATETIME_FIELD,
  TGETWALKDOGCOPYINFO_MAXSINGLESCORE_FIELD,
  TGETWALKDOGCOPYINFO_MAXSINGLEKILL_FIELD
}
TGETWALKDOGCOPYINFO.is_extendable = false
TGETWALKDOGCOPYINFO.extensions = {}
TGetWalkDogCopyInfo = protobuf.Message(TGETWALKDOGCOPYINFO)
return _ENV
