local protobuf = require("net.protobuf.protobuf")
webapi_pb = {}
local m = webapi_pb
local g = _G
local rawget = _ENV.rawget
local rawset = _ENV.rawset
_ENV = setmetatable({}, {
  __index = function(t, k)
    return rawget(m, k) or rawget(g, k)
  end,
  __newindex = m
})
TLUAINFO = protobuf.Descriptor()
local TLUAINFO_LUASTRING_FIELD = protobuf.FieldDescriptor()
TKEYVALUE = protobuf.Descriptor()
local TKEYVALUE_KEY_FIELD = protobuf.FieldDescriptor()
local TKEYVALUE_STRVALUE_FIELD = protobuf.FieldDescriptor()
local TKEYVALUE_NUMVALUE_FIELD = protobuf.FieldDescriptor()
TARGSLUARUN = protobuf.Descriptor()
local TARGSLUARUN_RESULTS_FIELD = protobuf.FieldDescriptor()
TLUAINFO_LUASTRING_FIELD.name = "LuaString"
TLUAINFO_LUASTRING_FIELD.full_name = ".pb.TLuaInfo.LuaString"
TLUAINFO_LUASTRING_FIELD.number = 1
TLUAINFO_LUASTRING_FIELD.index = 0
TLUAINFO_LUASTRING_FIELD.label = 1
TLUAINFO_LUASTRING_FIELD.has_default_value = false
TLUAINFO_LUASTRING_FIELD.default_value = nil
TLUAINFO_LUASTRING_FIELD.type = 9
TLUAINFO_LUASTRING_FIELD.cpp_type = 9
TLUAINFO.name = "TLuaInfo"
TLUAINFO.full_name = ".pb.TLuaInfo"
TLUAINFO.nested_types = {}
TLUAINFO.enum_types = {}
TLUAINFO.fields = {TLUAINFO_LUASTRING_FIELD}
TLUAINFO.is_extendable = false
TLUAINFO.extensions = {}
TKEYVALUE_KEY_FIELD.name = "Key"
TKEYVALUE_KEY_FIELD.full_name = ".pb.TKeyValue.Key"
TKEYVALUE_KEY_FIELD.number = 1
TKEYVALUE_KEY_FIELD.index = 0
TKEYVALUE_KEY_FIELD.label = 1
TKEYVALUE_KEY_FIELD.has_default_value = false
TKEYVALUE_KEY_FIELD.default_value = nil
TKEYVALUE_KEY_FIELD.type = 9
TKEYVALUE_KEY_FIELD.cpp_type = 9
TKEYVALUE_STRVALUE_FIELD.name = "StrValue"
TKEYVALUE_STRVALUE_FIELD.full_name = ".pb.TKeyValue.StrValue"
TKEYVALUE_STRVALUE_FIELD.number = 2
TKEYVALUE_STRVALUE_FIELD.index = 1
TKEYVALUE_STRVALUE_FIELD.label = 1
TKEYVALUE_STRVALUE_FIELD.has_default_value = false
TKEYVALUE_STRVALUE_FIELD.default_value = nil
TKEYVALUE_STRVALUE_FIELD.type = 9
TKEYVALUE_STRVALUE_FIELD.cpp_type = 9
TKEYVALUE_NUMVALUE_FIELD.name = "NumValue"
TKEYVALUE_NUMVALUE_FIELD.full_name = ".pb.TKeyValue.NumValue"
TKEYVALUE_NUMVALUE_FIELD.number = 3
TKEYVALUE_NUMVALUE_FIELD.index = 2
TKEYVALUE_NUMVALUE_FIELD.label = 1
TKEYVALUE_NUMVALUE_FIELD.has_default_value = false
TKEYVALUE_NUMVALUE_FIELD.default_value = nil
TKEYVALUE_NUMVALUE_FIELD.type = 5
TKEYVALUE_NUMVALUE_FIELD.cpp_type = 1
TKEYVALUE.name = "TKeyValue"
TKEYVALUE.full_name = ".pb.TKeyValue"
TKEYVALUE.nested_types = {}
TKEYVALUE.enum_types = {}
TKEYVALUE.fields = {
  TKEYVALUE_KEY_FIELD,
  TKEYVALUE_STRVALUE_FIELD,
  TKEYVALUE_NUMVALUE_FIELD
}
TKEYVALUE.is_extendable = false
TKEYVALUE.extensions = {}
TARGSLUARUN_RESULTS_FIELD.name = "Results"
TARGSLUARUN_RESULTS_FIELD.full_name = ".pb.TArgsLuaRun.Results"
TARGSLUARUN_RESULTS_FIELD.number = 1
TARGSLUARUN_RESULTS_FIELD.index = 0
TARGSLUARUN_RESULTS_FIELD.label = 3
TARGSLUARUN_RESULTS_FIELD.has_default_value = false
TARGSLUARUN_RESULTS_FIELD.default_value = {}
TARGSLUARUN_RESULTS_FIELD.message_type = TKEYVALUE
TARGSLUARUN_RESULTS_FIELD.type = 11
TARGSLUARUN_RESULTS_FIELD.cpp_type = 10
TARGSLUARUN.name = "TArgsLuaRun"
TARGSLUARUN.full_name = ".pb.TArgsLuaRun"
TARGSLUARUN.nested_types = {}
TARGSLUARUN.enum_types = {}
TARGSLUARUN.fields = {TARGSLUARUN_RESULTS_FIELD}
TARGSLUARUN.is_extendable = false
TARGSLUARUN.extensions = {}
TArgsLuaRun = protobuf.Message(TARGSLUARUN)
TKeyValue = protobuf.Message(TKEYVALUE)
TLuaInfo = protobuf.Message(TLUAINFO)
