LuaCSharpEvent = {}
local m = LuaCSharpEvent
local g = _G
local rawget = _ENV.rawget
local rawset = _ENV.rawset
_ENV = setmetatable({}, {
  __index = function(t, k)
    return rawget(m, k) or rawget(g, k)
  end,
  __newindex = m
})
local start = 300000
FleetPos = start + 1
SettlementItemCreate = start + 3
SettlementDataChangeBefore = start + 4
SettlementDataChangeAfter = start + 5
SettlementExpTweenBegin = start + 6
SettlementShowNextButton = start + 7
SettlementSlider = start + 8
SettlementEvaluationOpen = start + 9
SettlementEvaluationClose = start + 10
ShowSubtitle = start + 11
CloseSubtitle = start + 12
StageEnter = start + 13
LeaveStage = start + 14
SettlementChangeEnd = start + 15
TimelineFinish = start + 16
SaveChatInfo = start + 17
GuideTriggerPoint = start + 18
PlayAnimStart = start + 19
BattleNetDisconnect = start + 20
GuideUserOpe = start + 21
GuideInterrupt = start + 22
WaitOverBackLogin = start + 23
LoadingBattleKick = start + 24
TimelineChangeScene = start + 25
RecordBehaviour = start + 26
ShowGirlEffect = start + 27
ShowGirlStopAction = start + 28
ShowGirlContinueAction = start + 29
SupportFleetFinish = start + 30
LoginOk = start + 31
LoseFocus = start + 32
QualityAutoReduce = start + 33
Trigger3dTouch = start + 34
CarouselImage = start + 35
FaceTracked = start + 36
ARCanPut = start + 37
ARPutConfirm = start + 38
ShowStartBattle = start + 39
ARStartFill = start + 40
ARBrightness = start + 41
ARBattleResult = start + 42
TryPlaySettlementPSkillAnim = start + 43
ARFlushGirlPosition = start + 44
GuideFireTorpedo = start + 45
SettlementTryAutoExe = start + 46
SettlementTurnOnOffCamera = start + 47
TryStopVoice = start + 48
InitLocalChat = start + 49
EnhanceIndex = start + 50
MainSceneCharacterShadowFocus = start + 51
BaseBuildingPlotOver = start + 52
BaseBuildingCommon = start + 53
OnWaitBegin = start + 54
OnWaitEnd = start + 55
PlotEnd = start + 56
PressBack = start + 57
GuideCall = start + 58
NvNFleetSelected = start + 59
