local gachaInfo = {
    DrawInfo = {},
    DispInfo = {
        { Id = 1,    Count = 0 },
        { Id = 10,   Count = 0 },
        { Id = 1000, Count = 0 },
        { Id = 1001, Count = 0 },
        { Id = 1002, Count = 0 },
        { Id = 1003, Count = 0 },
        { Id = 1004, Count = 0 },
        { Id = 1005, Count = 0 },
        { Id = 1006, Count = 0 },
        { Id = 1007, Count = 0 },
        { Id = 101,  Count = 0 },
        { Id = 102,  Count = 0 },
        { Id = 103,  Count = 0 },
        { Id = 104,  Count = 0 },
        { Id = 105,  Count = 0 },
        { Id = 106,  Count = 0 },
        { Id = 107,  Count = 0 },
        { Id = 108,  Count = 0 },
        { Id = 109,  Count = 0 },
        { Id = 11,   Count = 0 },
        { Id = 110,  Count = 0 },
        { Id = 111,  Count = 0 },
        { Id = 112,  Count = 0 },
        { Id = 113,  Count = 0 },
        { Id = 114,  Count = 0 },
        { Id = 12,   Count = 0 },
        { Id = 13,   Count = 0 },
        { Id = 14,   Count = 0 },
        { Id = 15,   Count = 0 },
        { Id = 150,  Count = 0 },
        { Id = 16,   Count = 0 },
        { Id = 17,   Count = 0 },
        { Id = 18,   Count = 0 },
        { Id = 19,   Count = 0 },
        { Id = 2,    Count = 0 },
        { Id = 20,   Count = 0 },
        { Id = 2000, Count = 0 },
        { Id = 2001, Count = 0 },
        { Id = 2002, Count = 0 },
        { Id = 2003, Count = 0 },
        { Id = 2004, Count = 0 },
        { Id = 2005, Count = 0 },
        { Id = 2006, Count = 0 },
        { Id = 2007, Count = 0 },
        { Id = 201,  Count = 0 },
        { Id = 202,  Count = 0 },
        { Id = 203,  Count = 0 },
        { Id = 204,  Count = 0 },
        { Id = 205,  Count = 0 },
        { Id = 206,  Count = 0 },
        { Id = 207,  Count = 0 },
        { Id = 208,  Count = 0 },
        { Id = 209,  Count = 0 },
        { Id = 21,   Count = 0 },
        { Id = 22,   Count = 0 },
        { Id = 23,   Count = 0 },
        { Id = 3,    Count = 0 },
        { Id = 32,   Count = 0 },
        { Id = 33,   Count = 0 },
        { Id = 39,   Count = 0 },
        { Id = 4,    Count = 0 },
        { Id = 400,  Count = 0 },
        { Id = 43,   Count = 0 },
        { Id = 47,   Count = 0 },
        { Id = 5,    Count = 0 },
        { Id = 50,   Count = 0 },
        { Id = 51,   Count = 0 },
        { Id = 52,   Count = 0 },
        { Id = 53,   Count = 0 },
        { Id = 54,   Count = 0 },
        { Id = 55,   Count = 0 },
        { Id = 56,   Count = 0 },
        { Id = 57,   Count = 0 },
        { Id = 58,   Count = 0 },
        { Id = 6,    Count = 0 },
        { Id = 60,   Count = 0 },
        { Id = 7,    Count = 0 },
        { Id = 8,    Count = 0 },
        { Id = 9,    Count = 0 },
    },
    RefreshInfo = {},
    TotalCount = {},
    SpecialInfo = {},
    UsedRewardInfo = {},
    UsedBoxInfo = {},
    CloseTime = {},
    RewardChange = {}
}

return gachaInfo
