return {
  ["Netease MuMu"] = {level = 2, instancingBug = 1},
  ["Tencent virtual machine"] = {level = 0},
  ["HUAWEI EVA%-AL00"] = {level = 0},
  ["HUAWEI EVA%-AL10"] = {level = 0},
  ["HUAWEI VIE%-AL10"] = {level = 0},
  ["HUAWEI NXT%-AL10"] = {level = 0},
  ["HUAWEI DUK%-AL20"] = {level = 1},
  ["OPPO PACM00"] = {level = 1},
  ["OPPO PACT00"] = {level = 1},
  ["OPPO PADM00"] = {level = 1},
  ["OPPO PADT00"] = {level = 1},
  ["OPPO PBBM00"] = {level = 1},
  ["OPPO A73"] = {level = 0},
  ["OPPO A83"] = {level = 0},
  ["OPPO V1813A"] = {level = 1},
  ["OPPO V1813T"] = {level = 1},
  ["Xiaomi Redmi Note 4"] = {level = 0},
  ["vivo Y75"] = {level = 0},
  ["Meizu S6"] = {level = 0},
  ["iPhone10,3"] = {level = 1, unsafeOffset = -36},
  iPhone11 = {unsafeOffset = -36},
  iPad8 = {highFps = 1, hideAR = 1},
  ["OUKITEL C15 Pro"] = {isReflectionProbeBug = 1},
  ["Sony SO%-01G"] = {isReflectionProbeBug = 1},
  ["Sony SO%-01H"] = {isReflectionProbeBug = 1},
  ["Sony SO%-03H"] = {isReflectionProbeBug = 1},
  ["samsung SC%-04J"] = {isReflectionProbeBug = 1},
  ["HUAWEI HW%-01K"] = {level = 1, isReflectionProbeBug = 1},
  ["HUAWEI LYA%-L09"] = {isReflectionProbeBug = 1},
  ["SHARP SH%-01K"] = {isReflectionProbeBug = 1},
  ["samsung SC%-02M"] = {level = 0, isReflectionProbeBug = 1},
  ["samsung SC%-02L"] = {level = 1, isReflectionProbeBug = 1},
  ["samsung SCV43"] = {level = 0, isReflectionProbeBug = 1},
  ["SHARP SHV39"] = {level = 1}
}
