local GuideBehaviourManager = class("game.Guide.GuideBehaviours.GuideBehaviourManager")

function GuideBehaviourManager:initialize()
  self.tblBehaviourHand = {}
  self:initBehaviourHand()
end

function GuideBehaviourManager:initBehaviourHand()
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ENTER_BATTLE] = require("game.guide.guideBehaviours.enterbattle")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHOW_NOTICE] = require("game.guide.guideBehaviours.showNotice")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.GUIDE_TPOINT] = require("game.guide.guideBehaviours.guideTPoint")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.TORPEDO_FILL] = require("game.guide.guideBehaviours.torpedofill")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.PAUSE_BATTLE] = require("game.guide.guideBehaviours.pauseBattle")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.RESUME_BATTLE] = require("game.guide.guideBehaviours.resumeBattle")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHOW_BLACK_MASK] = require("game.guide.guideBehaviours.showBlackMask")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHOW_GUIDE_GIRL] = require("game.guide.guideBehaviours.showGuideGirl")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.DISABLE_SKILL] = require("game.guide.guideBehaviours.DisableSkill")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.CANCEL_DISABLE_SKILL] = require("game.guide.guideBehaviours.CancelDisableSkill")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.RESET_AIR_ATTACK_CD] = require("game.guide.guideBehaviours.ResetAirAttackCD")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.CAN_OPERATE] = require("game.guide.guideBehaviours.CanOperate")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.CAN_NOT_OPERATE] = require("game.guide.guideBehaviours.CannotOperate")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.PART_OPERATE] = require("game.guide.guideBehaviours.PartOperate")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SELECT_COPY] = require("game.guide.guideBehaviours.SelectCopy")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.OPEN_MAINLINE] = require("game.guide.guideBehaviours.OpenMainLine")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.TORPEDO_STOP] = require("game.guide.guideBehaviours.TorpedoStop")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.FLEET_CAN_MOVE] = require("game.guide.guideBehaviours.FleetCanMove")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.MID_TIP] = require("game.guide.guideBehaviours.MidTip")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SET_PLAYER_SPEED] = require("game.guide.guideBehaviours.SetPlayerSpeed")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHOW_SIMPLE_TIP] = require("game.guide.guideBehaviours.ShowSimpleTip")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.HIDE_SIMPLE_TIP] = require("game.guide.guideBehaviours.hideSimpleTip")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHOW_AIRATTACK_TIP] = require("game.guide.guideBehaviours.ShowAirAttackTip")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.NPC_CAN_MOVE] = require("game.guide.guideBehaviours.NpcCanMove")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHOW_OPTIONAL_BTN] = require("game.guide.guideBehaviours.ShowOptionalBtn")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SET_FATIGUE] = require("game.guide.guideBehaviours.SetFatigue")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.PAUSE_BATTLE_LATER] = require("game.guide.GuideBehaviours.PauseBattleLater")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.BATTLE_CAN_COST_TIME] = require("game.Guide.GuideBehaviours.CostTimeBehaviour")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.OPEN_HOME_PAGE] = require("game.Guide.GuideBehaviours.OpenHomePage")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.DONT_CLICK] = require("game.Guide.GuideBehaviours.OpenFleetLater")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SHIP_CANT_DRAG] = require("game.Guide.GuideBehaviours.ShipCantDrag")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SET_BAG_SORT_ALL] = require("game.guide.guideBehaviours.SetBagSortAll")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SET_SHIP_SORT_DEFAULT] = require("game.guide.guideBehaviours.SetShipSortDefault")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.USER_OPERA] = require("game.guide.guideBehaviours.UserOperate")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ENTER_NORMAL_BATTLE] = require("game.guide.guideBehaviours.EnterNormalCopy")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.PLOT] = require("game.guide.guideBehaviours.PlotBehaviour")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.OpenPage] = require("game.guide.guideBehaviours.OpenPage")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetFlagShip] = require("game.guide.guideBehaviours.SetFlagShipBehaviour")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ClosePage] = require("game.guide.guideBehaviours.ClosePageBehaviour")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.WaitTime] = require("game.guide.guideBehaviours.WaitTimeBehaviour")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ServiceReturn] = require("game.guide.guideBehaviours.WaitServiceCallMethod")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.UnLockShip] = require("game.guide.guideBehaviours.UnLockShip")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ClosePagesByLayer] = require("game.guide.guideBehaviours.ClosePagesByLayer")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.AddNewShip] = require("game.guide.guideBehaviours.AddNewShip")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.NpcCanAttack] = require("game.guide.guideBehaviours.NpcCanAttack")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.RepaireFleetOne] = require("game.guide.guideBehaviours.RepaireBehaviour")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ShowSpecial] = require("game.guide.guideBehaviours.ShowSpecial")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.StartFPSCheck] = require("game.guide.guideBehaviours.StartRecordFPS")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.CheckFPSResult] = require("game.guide.guideBehaviours.CheckFPSResult")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetCanPlayLogin] = require("game.guide.guideBehaviours.SetCanPlayLogin")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.WaitServiceEvent] = require("game.guide.guideBehaviours.WaitServiceEvent")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ShowComponent] = require("game.guide.guideBehaviours.ShowComponent")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.HideComponent] = require("game.guide.guideBehaviours.HideComponent")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.PlayAudio] = require("game.guide.guideBehaviours.PlayAudio")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.EnterStage] = require("game.guide.guideBehaviours.EnterStage")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SwitchKeyboard] = require("game.guide.guideBehaviours.SwitchKeyboard")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.TorpedoInsure] = require("game.guide.guideBehaviours.TorpedoInsure")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ResetCurTorpedo] = require("game.guide.guideBehaviours.ResetCurTorpedo")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.TraceCurTorpedo] = require("game.guide.guideBehaviours.TraceCurTorpedo")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ValidCurTorpedo] = require("game.guide.guideBehaviours.ValidCurTorpedo")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ReopenBattleSubUI] = require("game.guide.guideBehaviours.ReOpenBattleSubUI")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetGuidePageSort] = require("game.guide.guideBehaviours.SetGuidePageSort")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetFleetPageCanMove] = require("game.guide.guideBehaviours.SetFleetPageCanMove")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetBuildPageTog] = require("game.guide.guideBehaviours.SetBuildPageTog")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetObjActive] = require("game.guide.guideBehaviours.SetObjActive")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SetGuideInfluenceData] = require("game.guide.guideBehaviours.SetGuideInfluenceData")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ChangeCopyPageTog] = require("game.guide.guideBehaviours.ChangeCopyPageTog")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.BuildingMainToRight] = require("game.guide.guideBehaviours.BuildingMainToRight")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.TowerMainToEnd] = require("game.guide.guideBehaviours.TowerMainToEnd")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SearchCamModelToNear] = require("game.guide.guideBehaviours.SearchCamModelToNear")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.Switch3DCamMode] = require("game.guide.guideBehaviours.Switch3DCamMode")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.BuildingMainToLeft] = require("game.guide.guideBehaviours.BuildingMainToLeft")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.AllowMoveInterval] = require("game.guide.guideBehaviours.AllowMoveInterval")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.RefreshFleetItem] = require("game.guide.guideBehaviours.RefreshFleetItem")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ClickLevelFleetItemTrick] = require("game.guide.guideBehaviours.ClickLevelFleetItemTrick")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.ClickFleetFirstGirlTrick] = require("game.guide.guideBehaviours.ClickFleetFirstGirlTrick")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.SwitchGirlinfoTag] = require("game.guide.guideBehaviours.SwitchGirlinfoTag")
  self.tblBehaviourHand[GUIDE_BEHAVIOUR.RefreshTorpedoBtn] = require("game.guide.guideBehaviours.RefreshTorpedoBtn")
end

function GuideBehaviourManager:buildBehaviour(nType, objHolder, objParam)
  local objRequired = self.tblBehaviourHand[nType]
  if objRequired == nil then
    logError("cant find behaviour type " .. tostring(nType))
    return
  end
  local objResult = objRequired:new(nType, objHolder, objParam)
  return objResult
end

return GuideBehaviourManager
